### ISSUE TITLE
Add licenses to Markdown

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-rust#10]
I noticed that we ignore markdown files: https://github.com/apache/iceberg-rust/blob/106be6f5ddd87423dbb1b56cf7ed2d403ee48ad1/.licenserc.yaml#L26

Let's also add the markdown, similar to PyIceberg: https://github.com/apache/iceberg/blob/master/python/mkdocs/docs/api.md

**Comment by Xuanwo** [comment]
Wow, I didn't know we could add a license header in Markdown!
