### ISSUE TITLE
bug: ManifestList parsing should not require `partition_type`.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#121]
In [manifest list parser](https://github.com/apache/iceberg-rust/blob/82e129945bed150b6d9fbcb93ebb4d92f8150895/crates/iceberg/src/spec/manifest_list.rs#L57), we ask user to pass in a `partition_type`. This is incorrect since different manifest file may have different partition spec, so we should ask user to pass a `HashMap<i32, StructType>`, e.g. a mapping from partition spec id to partition type. See https://iceberg.apache.org/spec/#snapshots

**Comment by liurenjie1024** [comment]
cc @ZENOTME

**Comment by ZENOTME** [comment]
Thanks! I will send a PR to fix it later.
