### ISSUE TITLE
field-id in avro schema is missing

### ISSUE THREAD

**Issue by ZENOTME** [apache/iceberg-rust#131]
According https://github.com/risingwavelabs/risingwave/issues/14106, avro-rs don't serialize the field-id. We will close this issue after the fix be accept by upstream and release it.

**Comment by liurenjie1024** [comment]
It would be better to link apache avro rust issue here so that we can track it.

**Comment by ZENOTME** [comment]
Track in https://issues.apache.org/jira/browse/AVRO-3920

**Comment by sdd** [comment]
This appears to have been resolved: https://issues.apache.org/jira/browse/AVRO-3920

**Comment by ZENOTME** [comment]
> Thanks @ZENOTME for this pr: [apache/avro#2650](https://github.com/apache/avro/pull/2650) But I think we should still make this open since it has not been released yet? I think it will be included in 0.16.1 or 0.17?

Sorry, I forget that. I find that the last release of Avro-rust was 9 months ago, maybe we can ask them whether there is the plan to release 0.16.1 or 0.17 recently.

**Comment by ZENOTME** [comment]
New info for Avro 0.17: https://issues.apache.org/jira/browse/AVRO-4001. It will be coming soon!

**Comment by Xuanwo** [comment]
This one can be closed?

**Comment by ZENOTME** [comment]
> This one can be closed?

I think we can close it now.
