### ISSUE TITLE
doc: Update README with roadmap and feature status.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#133]
Inspired by [iceberg-go](https://github.com/apache/iceberg-go), I feel that we may need a roadmap/status table in `README.md` to make the status more clear.

**Comment by liurenjie1024** [comment]
I'll work on this.

**Comment by Xuanwo** [comment]
Will you add non-jvm future of iceberg in README :laughing:

**Comment by liurenjie1024** [comment]
> Will you add non-jvm future of iceberg in README 😆

It's a too big picture😅
