### ISSUE TITLE
doc: rust.iceberg.apache.org is not resolved

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#137]
`rust.iceberg.apache.org` is not resolved, do we need to submit a ticket to infra?

```shell
:) drill rust.iceberg.apache.org
;; ->>HEADER<<- opcode: QUERY, rcode: NXDOMAIN, id: 27319
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; rust.iceberg.apache.org.     IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
apache.org.     598     IN      SOA     ns-558.awsdns-05.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Dec 26 19:59:10 2023
;; MSG SIZE  rcvd: 125
```

cc @Fokko @bitsondatadev

**Comment by liurenjie1024** [comment]
Seems dns record added:
```
dig rust.iceberg.apache.org

; <<>> DiG 9.10.6 <<>> rust.iceberg.apache.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51032
;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0001, udp: 4096
;; QUESTION SECTION:
;rust.iceberg.apache.org.	IN	A

;; ANSWER SECTION:
rust.iceberg.apache.org. 1	IN	A	198.10.0.19

;; Query time: 102 msec
;; SERVER: 198.10.0.2#53(198.10.0.2)
;; WHEN: Wed Dec 27 10:46:44 CST 2023
;; MSG SIZE  rcvd: 91

```

**Comment by liurenjie1024** [comment]
But I can't open the page

**Comment by Xuanwo** [comment]
> Seems dns record added:
> 
> ```
> dig rust.iceberg.apache.org
> 
> ; <<>> DiG 9.10.6 <<>> rust.iceberg.apache.org
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51032
> ;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; MBZ: 0x0001, udp: 4096
> ;; QUESTION SECTION:
> ;rust.iceberg.apache.org.	IN	A
> 
> ;; ANSWER SECTION:
> rust.iceberg.apache.org. 1	IN	A	198.10.0.19
> 
> ;; Query time: 102 msec
> ;; SERVER: 198.10.0.2#53(198.10.0.2)
> ;; WHEN: Wed Dec 27 10:46:44 CST 2023
> ;; MSG SIZE  rcvd: 91
> ```

Hi, `198.10.0.19` seems not a valid DNS answer especially when it reported by `198.10.0.2`. Would you like to try `dig rust.iceberg.apache.org @8.8.8.8`?

**Comment by liurenjie1024** [comment]
I can't reach to 8.8.8.8🥵

**Comment by Xuanwo** [comment]
> I can't reach to 8.8.8.8🥵

Please try `114.114.114.114` or `223.5.5.5`

**Comment by liurenjie1024** [comment]
Seems not resolved:
```
dig @114.114.114.114 rust.iceberg.apache.org

; <<>> DiG 9.10.6 <<>> @114.114.114.114 rust.iceberg.apache.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 46499
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;rust.iceberg.apache.org.	IN	A

;; AUTHORITY SECTION:
apache.org.		900	IN	SOA	ns-558.awsdns-05.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 79 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Wed Dec 27 14:35:53 CST 2023
;; MSG SIZE  rcvd: 125

```

**Comment by amogh-jahagirdar** [comment]
Reopening, the domain still seems to be an issue, although maybe a different issue. after merging #138 I got the following email:

```
An error occurred while running publish feature in .asf.yaml!:
.asf.yaml: Invalid hostname '[rust.iceberg.apache.org](http://rust.iceberg.apache.org/)' - you cannot specify *.[apache.org](http://apache.org/) hostnames, they must be inferred!
```

**Comment by liurenjie1024** [comment]
Should we involve apache infra team to help debugging?

**Comment by liurenjie1024** [comment]
Seems still not working. Do we have any way to debug this?

**Comment by Fokko** [comment]
Thanks for raising an issue: https://issues.apache.org/jira/browse/INFRA-25338

It looks good as far as I can see.

**Comment by Xuanwo** [comment]
https://rust.iceberg.apache.org/ is online!
