### ISSUE TITLE
bug: Iceberg decimal should be converted to fixed in avro.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#144]
See  [spec](https://iceberg.apache.org/spec/#avro).

The difference between `fixed` and `bytes` is that in avro format, `bytes` data is prepended with a long value for it size, while it doesn't exists for for `fixed` type.

**Comment by Fokko** [comment]
Great catch @liurenjie1024. It is stored as a fixed with the minimal number of bytes required to store the full precision of the type. An example how it is done in Python: https://github.com/apache/iceberg-python/blob/5af05bd57c94667e3760423fcdac5f9ce9e5ca6e/pyiceberg/utils/decimal.py#L111-L127

**Comment by liurenjie1024** [comment]
> Great catch @liurenjie1024. It is stored as a fixed with the minimal number of bytes required to store the full precision of the type. An example how it is done in Python: https://github.com/apache/iceberg-python/blob/5af05bd57c94667e3760423fcdac5f9ce9e5ca6e/pyiceberg/utils/decimal.py#L111-L127

Yeah, it took me two days to figure out😅
