### ISSUE TITLE
feat: Implement expression rewriter to remove `NOT` operator.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#150]

**Comment by sdd** [comment]
@liurenjie1024 could you assign this task to me please? :-)

**Comment by liurenjie1024** [comment]
> @liurenjie1024 could you assign this task to me please? :-)

Yes, sure. Thanks for contributing!

**Comment by liurenjie1024** [comment]
Hi, @marvinlanhenke I think your pr is right about this. `rewrite_not` is based on the `negate` api.
