### ISSUE TITLE
feat: Implement expression projection evaluator.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#151]
See [python implementation](https://github.com/apache/iceberg-python/blob/afdfa351119090f09d38ef72857d6303e691f5ad/pyiceberg/expressions/visitors.py#L828)

This step projects row filter to partition value filter.

Blocked by #264.

**Comment by TennyZhuang** [comment]
I’ll work on this

**Comment by liurenjie1024** [comment]
Duplicate with #152
