### ISSUE TITLE
feat: Implement data file metrics evaluator to prune data files using filter.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#152]
See [python implementation](https://github.com/apache/iceberg-python/blob/afdfa351119090f09d38ef72857d6303e691f5ad/pyiceberg/expressions/visitors.py#L460) 

Used to evaluate partition filter.

Blocked by #264 #151

**Comment by sdd** [comment]
@liurenjie1024 this is now done, since https://github.com/apache/iceberg-rust/pull/347 got merged.
