### ISSUE TITLE
Add the homepage to the `Cargo.toml`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-rust#154]
Looks like we can add the homepage as well: https://doc.rust-lang.org/cargo/reference/manifest.html#the-homepage-field

To our newly created https://rust.iceberg.apache.org/

**Comment by Xuanwo** [comment]
Marked as good first issues for new contributors to get started 🥰

**Comment by hiirrxnn** [comment]
Can i work on this ? Let me know what is to be done here .

**Comment by hiirrxnn** [comment]
Just wanted to confirm , is : https://rust.iceberg.apache.org/ the homepage i'm required to add ?  Correct me if I'm wrong .

**Comment by liurenjie1024** [comment]
> Just wanted to confirm , is : https://iceberg.apache.org the homepage i'm required to add ? Correct me if I'm wrong .

No, it's https://rust.iceberg.apache.org/

**Comment by liurenjie1024** [comment]
Closed by #160
