### ISSUE TITLE
refactor: Remove support of manifest list format as a list of file paths.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#158]
Do you think it's a good idea to check this first so we don't need to write in enum pattern matching?

_Originally posted by @Xuanwo in https://github.com/apache/iceberg-rust/pull/129#discussion_r1445548092_
            
As we don't plan to support the manifest list as manifest list file, we will remove support for it.

**Comment by hiirrxnn** [comment]
Could I work on this?

**Comment by liurenjie1024** [comment]
> Could I work on this?

Sure, thanks for contributing! @hiirrxnn

**Comment by hiirrxnn** [comment]
Which file/files should I make this change in ?

**Comment by liurenjie1024** [comment]
See this: https://github.com/apache/iceberg-rust/blob/c91aeaec2aa713a1efdc513e1769220dd53cf443/crates/iceberg/src/spec/snapshot.rs#L98

You can remove the enum, but it may requires modifying some places to get it compiled.

**Comment by Dysprosium0626** [comment]
https://github.com/Dysprosium0626/iceberg-rust/commit/e25adbb07a1fb03a856dc40cfa90c3e253281af9

Hi @liurenjie1024, here is my version of refactor. I just remove the enum and all the `ManifestListLocation::ManifestFiles` and change `ManifestListLocation::ManifestListFile` to `String`.

**Comment by liurenjie1024** [comment]
Hi, @Dysprosium0626 That looks great to me! Welcome to contribute.

**Comment by Dysprosium0626** [comment]
Hi, you may close this issue now!
(BTW It looks like some of the issues like https://github.com/apache/iceberg-rust/issues/192 could be close too)
