### ISSUE TITLE
Add format check for toml files.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#161]
As suggested by @Xuanwo , we can use taplo to format toml file.

**Comment by Tyler-Sch** [comment]
Would something like [this ](https://github.com/apache/iceberg-rust/pull/167) work?

**Comment by liurenjie1024** [comment]
> Would something like [this ](https://github.com/apache/iceberg-rust/pull/167) work?

Yes, thanks for contributing!

**Comment by liurenjie1024** [comment]
Closed by #167
