### ISSUE TITLE
TableCommit builder's build method should be `pub`

### ISSUE THREAD

**Issue by zeodtr** [apache/iceberg-rust#164]
Hi,

Since `Catalog` trait is `pub`, any `struct` used in the `fn`s in the trait should be publically buildable.
But `TableCommit`'s builder's builder method's scope is explicitly set to `pub(crate)`.
So, the code out of the crate cannot call the `update_table()` `fn` since `TableCommit` cannot be built.
Is there any reason to limit the scope? Or is there any other way to build it?
If not, `TableCommit` builder's build method should be `pub`.

Thanks.

**Comment by zeodtr** [comment]
Hi, @liurenjie1024, I see. Thank you!

**Comment by zeodtr** [comment]
@liurenjie1024  Sorry, but there is another question.

I want to add a `Snapshot` to a `Table` but `Transaction` does not provide a `fn` to do it (`append_updates` is private). Is there another method to do that?

Thank you.

**Comment by liurenjie1024** [comment]
> @liurenjie1024 Sorry, but there is another question.
> 
> I want to add a `Snapshot` to a `Table` but `Transaction` does not provide a `fn` to do it (`append_updates` is private). Is there another method to do that?
> 
> Thank you.

Hi, @zeodtr It's in roadmap but not implemented yet.

**Comment by zeodtr** [comment]
@liurenjie1024  Thank you for your quick answer.

I'm currently implementing my own `Catalog` to handle my own Iceberg-compatible storage. If adding a snapshot cannot be done using `Catalog` interface, maybe I should do it without the `Catalog` interface for now.

Thank you.
