### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by Samrose-Ahmed** [apache/iceberg-rust#165]
I was testing the basic scan on some real data, found what I think is two bugs

1. One is this line (https://github.com/apache/iceberg-rust/blob/35f348139ac1697336244fffa4b4b24280ff79ce/crates/iceberg/src/spec/manifest.rs#L1364), it needs to be able to handle negative numbers, I had eg `null_value_counts` where value was `-1`, I think that can be mapped to 0 here.

2. In this function (https://github.com/apache/iceberg-rust/blob/35f348139ac1697336244fffa4b4b24280ff79ce/crates/iceberg/src/spec/manifest.rs#L1333) we shouldn't throw this error, but just skip if the field is not found, due to schema evolution.

**Comment by liurenjie1024** [comment]
Hi @Samrose-Ahmed  Sorry for late reply.

> One is this line (
> 
> [iceberg-rust/crates/iceberg/src/spec/manifest.rs](https://github.com/apache/iceberg-rust/blob/35f348139ac1697336244fffa4b4b24280ff79ce/crates/iceberg/src/spec/manifest.rs#L1364)
> 
> Line 1364 in [35f3481](https://github.com/apache/iceberg-rust/commit/35f348139ac1697336244fffa4b4b24280ff79ce)
> 
>  m.insert(entry.key, entry.value.try_into()?); 
> ), it needs to be able to handle negative numbers, I had eg null_value_counts where value was -1, I think that can be mapped to 0 here.

In what case this might be negative value, i.e. used for `null_value_counts`? Why counts may be negative value? cc @Fokko Any ideas?


> In this function (
> 
> [iceberg-rust/crates/iceberg/src/spec/manifest.rs](https://github.com/apache/iceberg-rust/blob/35f348139ac1697336244fffa4b4b24280ff79ce/crates/iceberg/src/spec/manifest.rs#L1333)
> 
> Line 1333 in [35f3481](https://github.com/apache/iceberg-rust/commit/35f348139ac1697336244fffa4b4b24280ff79ce)
> 
>  .ok_or_else(|| { 
> ) we shouldn't throw this error, but just skip if the field is not found, due to schema evolution. 

Sound reasonable to me. I will fix it.

**Comment by Samrose-Ahmed** [comment]
Yeah I think discarding makes sense. this table was written by the Iceberg Java library and I've read it with spark and trino.

**Comment by liurenjie1024** [comment]
This bug has been fixed, could you have another try? cc @Samrose-Ahmed
