### ISSUE TITLE
Add `Sync + Send` to `Catalog` `trait`

### ISSUE THREAD

**Issue by zeodtr** [apache/iceberg-rust#166]
Hi,

Currently `Catalog` `trait` only has `std::Debug` as a requirement.
So, when I try to add an instance of a `Catalog` (such as `Arc<dyn Catalog>`) as a field of a `struct` that is related to async operations, compilation fails with the following error: "`(dyn Catalog + 'static)` cannot be shared between threads safely".
It would be nice to add `Sync + Send` to `Catalog` `trait` to allow this.

If this matter is too trivial for a formal issue, I can discuss it on the Iceberg Slack channel instead.

Thank you.

**Comment by liurenjie1024** [comment]
This idea sounds good too me. `Catalog` is supposed to be safe to be shared between threads.

**Comment by Xuanwo** [comment]
> This idea sounds good too me. `Catalog` is supposed to be safe to be shared between threads.

LTGM, let me do this.
