### ISSUE TITLE
Remove `unwrap()` in `ManifestListWriter.close()`

### ISSUE THREAD

**Issue by zeodtr** [apache/iceberg-rust#177]
`unwrap()` should not be used in normal code, but `ManifestListWriter.close()` uses it.
It should be removed and the error should be properly handled like `ManifestWriter.write()`.

**Comment by liurenjie1024** [comment]
Thanks for reporting!

**Comment by zeodtr** [comment]
@Fokko @liurenjie1024  I think this issue has not been resolved, since I'm kind of disagree with the pull request.
What I'm concerned about are as follows:
* `expect()` also should not be used since it ends the program with panic just like `unwrap()`. In a production program that's unacceptable, especially for a server program.
* It might not be enough to just replace `unwrap()` with `?` in `ManifestListWriter`'s write-related codes. In `ManifestWriter`, it also adds an appropriate error message.   Please see: https://github.com/apache/iceberg-rust/blob/9ae9e13fb48ea8af20d76644f27dcb2fc8773396/crates/iceberg/src/spec/manifest.rs#L295

Could you please reopen this issue?

**Comment by liurenjie1024** [comment]
@zeodtr  Sorry for the mistake, yes you are right, expect still may cause panic. Let's reopen it. cc @odysa We may need to modify the `From` to `TryFrom`.

**Comment by odysa** [comment]
> We may need to modify the From to TryFrom.

`serde` does not support the attribute `try_into`. https://github.com/serde-rs/serde/issues/1524  The `into` attribute requires `From`. Converting to `TryFrom` requires us to manually implement a serializer.
https://github.com/apache/iceberg-rust/blob/9ae9e13fb48ea8af20d76644f27dcb2fc8773396/crates/iceberg/src/spec/table_metadata.rs#L48

**Comment by liurenjie1024** [comment]
I remember why we use `expect` for `TableMetadata` serialization, see [this comment](https://github.com/apache/iceberg-rust/blob/c91aeaec2aa713a1efdc513e1769220dd53cf443/crates/iceberg/src/spec/table_metadata.rs#L51). But I still agree that it would be best not to panic in a serious lib which may crash programs.


>serde does not support the attribute try_into. https://github.com/serde-rs/serde/issues/1524 The into attribute requires From. Converting to TryFrom requires us to manually implement a serializer.

Yes, it seems we still need to implement Serialization/Deserialization manually, but it's still a wrapper of the conversion from `TableMetadataEnum`.

**Comment by zeodtr** [comment]
In the following code, from: https://github.com/apache/iceberg-rust/blob/9ae9e13fb48ea8af20d76644f27dcb2fc8773396/crates/iceberg/src/spec/table_metadata.rs#L679

```rust
    impl From<TableMetadata> for TableMetadataV1 {
        fn from(v: TableMetadata) -> Self {
            TableMetadataV1 {
                format_version: VersionNumber::<1>,
                table_uuid: Some(v.table_uuid),
                location: v.location,
                last_updated_ms: v.last_updated_ms,
                last_column_id: v.last_column_id,
                schema: v
                    .schemas
                    .get(&v.current_schema_id)
                    .expect("current_schema_id not found in schemas")
                    .as_ref()
                    .clone()
                    .into(),

```

The code `expect()`s `current_schema_id` should not be `None`. But it is valid to be` None` in `TableMetadataV1`, although such usage is deprecated. (See Iceberg spec https://iceberg.apache.org/spec/#table-metadata-fields) I think that using `expect()` is unacceptable in such a case. Actually, in this case, I think that the code should instead use the `schema` field of `TableMetadataV1` when the `current_schema_id` field is `None`.

**Comment by odysa** [comment]
> The code expect()s current_schema_id should not be None

`current_schema_id` is impossible to be `None` in `TableMetadata`

> But it is valid to be None in TableMetadataV1

It's handled here.
https://github.com/apache/iceberg-rust/blob/9ae9e13fb48ea8af20d76644f27dcb2fc8773396/crates/iceberg/src/spec/table_metadata.rs#L556

>  code should instead use the schema field of TableMetadataV1 when the current_schema_id field is None

When we convert `TableMetadata` to `TableMetadataV1`, we have to look up `schemas` since there is no `schema` field in `TableMetadata`

> expect() is unacceptable in such a case

I agree. It panics only when `schemas` does not contain `current_schema_id`, which means `TableMetadataV1` may be invalid.

**Comment by zeodtr** [comment]
@odysa Oh sorry, I totally misunderstood the code. Upon seeing the `expect()` message `"current_schema_id not found in schemas"`, I thought it's the case of `'current_schema_id == None'.`
Sorry again for the inconvenience.

**Comment by tabmatfournier** [comment]
Is this issue still valid given https://github.com/apache/iceberg-rust/pull/185 ?  This seems addressed.  Apologies for the noise, surfing good first issues for something to get started on.

**Comment by liurenjie1024** [comment]
> Is this issue still valid given #185 ? This seems addressed. Apologies for the noise, surfing good first issues for something to get started on.

@tabmatfournier Yeah, I think it's closed, thanks for reporting this.
