### ISSUE TITLE
Design of Serialization/Deserialization

### ISSUE THREAD

**Issue by JanKaul** [apache/iceberg-rust#2]
I would like to have a discussion about how to implement the Serialization/Deserialization of the iceberg metadata. There are currently two different designs each with its pros and cons. The designs are:

1. Split representation into in_memory/on_disk part ([example](https://github.com/icelake-io/icelake/blob/main/src/types/on_disk/types.rs#L53-L181))
2. Use custom implementations of `Serialize`/`Deserialize` ([example](https://github.com/JanKaul/iceberg-rust/blob/main/iceberg-rust/src/model/types.rs#L78-L92))

I would like to get your opinion which design you prefer.

**Comment by ZENOTME** [comment]
If I'm not mistaken, use the split representation also need to custom implementation for on_disk part. And we should maintain two system: in_memory::type, in_memory::value, on_disk::type, on_disk::value. And we also need to maintain the conversion between in_memory and on_disk. So I think strictly separate two part may cause redundant code. Can we only separate some part🤔?

**Comment by JanKaul** [comment]
I also think that a split representation leads to redundancy which makes maintaining the code more difficult.

I personally think that the added complexity of custom implementations of `Serialize`/`Deserialize` is worth avoiding the redundancy.

**Comment by JanKaul** [comment]
I realized that this discussion is closely related to #3 , because it gives additional motivation for splitting the representation into an in_memory and on_disk part.

I think @ZENOTME made a good point about splitting only a part of the metadata.

We could split the metadata for all structs that have user interaction (i.e. `TableMetadata`) but use a single representation for the smaller building blocks (i.e. types, values, ..)

**Comment by liurenjie1024** [comment]
Close this as we have finished discussion. Feel free to open if needed.
