### ISSUE TITLE
ci: Security audit failed due to rsa.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#221]
See [workflow](https://github.com/apache/iceberg-rust/actions/runs/8018117597/job/21903364175). We may need to wait for rsa to upgrade to fix it.

**Comment by liurenjie1024** [comment]
cc @Xuanwo Other opendal user confront this error?

**Comment by Xuanwo** [comment]
> cc @Xuanwo Other opendal user confront this error?

I'm guessing most of them just ignore it since nothing we can do about it.

**Comment by liurenjie1024** [comment]
Let's leave this open until rsa crate has been fixed.

**Comment by Xuanwo** [comment]
No actions to take so far, closing.
