### ISSUE TITLE
feat: Add `AlwaysTrue`/`AlwaysFalse` for `Predicate` enum.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#224]
See https://github.com/apache/iceberg-rust/pull/169#discussion_r1507941201 for details.

This is quite useful for expression rewrite.

**Comment by Dysprosium0626** [comment]
Is this block by https://github.com/apache/iceberg-rust/pull/169?
 I could work on this after this pr is merged.

**Comment by liurenjie1024** [comment]
> Is this block by #169? I could work on this after this pr is merged.

Hi, @Dysprosium0626  Yes, it's blocked by #169. Welcome to contribute!
