### ISSUE TITLE
Discussion: Design of `TableMetadataBuilder`.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#232]
# Problem statement

`TableMetadataBuilder` is useful in modifying/creating `TableMetadata`, and is a core data structure of transaction api. There are already some efforts to create one using derived builder, see https://github.com/apache/iceberg-rust/pull/62 and https://github.com/apache/iceberg-rust/pull/229. While it's easy to implement, I have some concerns about this approach. There are some problems with this approach:

1. Not easy to review. it's quite easy to forget that we have changed builder api when we do modification to `TableMetadata`.
2. Not easy to customize. I've checked the builder in [java api](https://github.com/apache/iceberg/blob/2e291c2b67a643ffe93e139483df55f3639cc39d/core/src/main/java/org/apache/iceberg/TableMetadata.java#L857), and it has a lot of customization in each method with validations.

The reason I want to be careful with `TableMetadataBuilder` is that it's a core data structure in iceberg, and we should not expose apis which be misused to construct inconsistent `TableMetadata`.

# Proposal

I want to propose to implement `TableMetadataBuilder` in a similar approach like [java api](https://github.com/apache/iceberg/blob/2e291c2b67a643ffe93e139483df55f3639cc39d/core/src/main/java/org/apache/iceberg/TableMetadata.java#L857), rather than using derived builder directly, such as following:
```rust
pub struct TableMetadataBuilder(TableMetadata);

impl TableMetadataBuilder {
   pub fn add_schema(mut self, schema: Schema) -> Result<Self> {
       // Check if schema validity
   }

  pub fn add_unbound_partition_spec(mut self, spec: UnboundPartitionSpec) -> Result<Self> { 
   // Binding partition spec
  }

  pub fn build(self) -> Result<TableMetadata> {}
}
```

**Comment by liurenjie1024** [comment]
cc @Xuanwo @ZENOTME @Fokko @JanKaul @y0psolo

**Comment by Xuanwo** [comment]
When `add_schema` has been called, both `schemas` and `current_schema_id` will be updated? The same question to `partition_specs`.

**Comment by liurenjie1024** [comment]
> When `add_schema` has been called, both `schemas` and `current_schema_id` will be updated? The same question to `partition_specs`.

Yes, the `add_schema` process consists of several steps as in [java implementation](https://github.com/apache/iceberg/blob/2e291c2b67a643ffe93e139483df55f3639cc39d/core/src/main/java/org/apache/iceberg/TableMetadata.java#L1449)

1. Check if already existed same schema.
2. If not, assign schema id to it.
3. Modify schemas.

Similar things happens for `partition_specs`.

Other methods such as [`setBranchSnapshot`](https://github.com/apache/iceberg/blob/2e291c2b67a643ffe93e139483df55f3639cc39d/core/src/main/java/org/apache/iceberg/TableMetadata.java#L1180) are also quite complicated.

**Comment by sdd** [comment]
I agree with @liurenjie1024. Looking at the Java implementation, it seems like there is too much going on here for a derived builder to be a good fit, and a hand-rolled builder would be more appropriate.

**Comment by ZENOTME** [comment]
> I want to propose to implement TableMetadataBuilder in a similar approach like [java api](https://github.com/apache/iceberg/blob/2e291c2b67a643ffe93e139483df55f3639cc39d/core/src/main/java/org/apache/iceberg/TableMetadata.java#L857), rather than using derived builder directly

Implementing the builder manually looks good to me.

**Comment by liurenjie1024** [comment]
Cool, seems we reached consensus on this, let's move on to create `TableMetadataBuilder`.

**Comment by marvinlanhenke** [comment]
what about supporting FormatVersion V1 and V2? Will we simply model V2 and provide all optional fields as well for V1 in order to simplify the struct TableMetadata (like it is right now?) - or would there be any reason to change that?

**Comment by liurenjie1024** [comment]
> what about supporting FormatVersion V1 and V2? Will we simply model V2 and provide all optional fields as well for V1 in order to simplify the struct TableMetadata (like it is right now?) - or would there be any reason to change that?

Sorry, I don't get your point. I think currently our approach is just like what you say, and we don't have plan to change it. Oh, you mean further modification to `TableMetadata` ? In fact, I mean the evolution of table metadata spec in future.

> Also how would we handle the update or modifications to an existing TableMetadata. Using TableMetadataBuilder for the controlled construction and implement the update methods directly on the TableMetadata could be one approach?

That's possible, but that means we need to implement the validation logic in two places, and I think we should avoid such duplication.

**Comment by marvinlanhenke** [comment]
> [...] and we don't have plan to change it

> That's possible, but that means we need to implement the validation logic in two places

Makes sense to me. thanks for clarifying.

**Comment by c-thiel** [comment]
@liurenjie1024, @Fokko  do you know if someone is working on a full implementation of the TableMetadataBuilder?
If not, I would prepare a PR a cleaned-up Version of what we have in the [Iceberg-Catalog](https://github.com/hansetag/iceberg-catalog) over to here. It's mostly about adding all modifications as addition of snapshots, schema evolution, partitioning, ordering, various validations, partition binding, etc.

**Comment by c-thiel** [comment]
@liurenjie1024 I would be interested to contribute.

Let me maybe start with partition binding - i.e. binding an `UnboundPartitionSpec` to a schema - making it a bound `PartitionSpec` or re-binding to a different schema on updates.

Do you have a strong feeling of where the code should go? As part of an `Action` or separately? If not, I would just make a proposal.

**Comment by Fokko** [comment]
Since we have a first version in https://github.com/apache/iceberg-rust/pull/587, I'll go ahead and close this issue
