### ISSUE TITLE
Rename `stat_table` to `table_exists` in `Catalog` trait.

### ISSUE THREAD

**Issue by marvinlanhenke** [apache/iceberg-rust#236]
## Problem Statement:
Name does not precisely convey its purpose (at least I thought so while working on the HMS catalog).
https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/catalog/mod.rs#L86

## Proposal:
Rename to:
- stat_table => table_exists (aligns with namespace_exists)

Best regards

**Comment by Xuanwo** [comment]
I remember that `stat_table` will also return some metadata of this table.

cc @Fokko @liurenjie1024, any comments?

**Comment by marvinlanhenke** [comment]
> I remember that `stat_table` will also return some metadata of this table.

I only took a look at the java & python hive implementation and I couldn't find a similiar table operation - but perhaps `stat_table` is used in a different catalag implementation that does indeed return the metadata.

**Comment by liurenjie1024** [comment]
Current implementation in fact only checks table exists, and it's also the operation id in rest catalog spec: https://github.com/apache/iceberg/blob/621d301b17417af4b71a0e8c93db9db6f8266839/open-api/rest-catalog-open-api.yaml#L778

So `is_table_exists` seems better to me.

**Comment by Fokko** [comment]
Thanks for raising this.

`stat_table` is not the most descriptive name to me. I would suggest a `table_exist(identifier)` method.

Information about the tables is typically exposed through [metadata tables](https://iceberg.apache.org/docs/latest/spark-queries/#querying-with-sql).

**Comment by marvinlanhenke** [comment]
@liurenjie1024 @Xuanwo 
Perhaps this would be a `good-first-issue` ?

marker:
https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/catalog/mod.rs#L86
