### ISSUE TITLE
Add OAuth Support for iceberg rest client.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#238]
The rest catalog openapi spec could be found here: https://github.com/apache/iceberg/blob/a582968975dd30ff4917fbbe999f1be903efac02/open-api

Python rest catalog client implementation could be found here: 
https://github.com/apache/iceberg-python/blob/b026c5d4b7ba5244f67733870c06c952923e6852/pyiceberg/catalog/rest.py

**Comment by TennyZhuang** [comment]
I’ll take a look on the issue

**Comment by TennyZhuang** [comment]
The python implementation is generated by their spec, do we really need to implement the rest client manually?

**Comment by TennyZhuang** [comment]
I'm ready to give it a try using some OpenAPI rust generators to create a client. If anyone has tried this before and encountered any issues, feel free to share them with me.

**Comment by liurenjie1024** [comment]
> The python implementation is generated by their spec, do we really need to implement the rest client manually?

Hi, are you looking at iceberg-python or generated Python module in iceberg repo? Codes in iceberg repo are only used for testing what's the model looks like and not used in production. The actual implementation could be found in link I mentioned above.

**Comment by liurenjie1024** [comment]
> I'm ready to give it a try using some OpenAPI rust generators to create a client. If anyone has tried this before and encountered any issues, feel free to share them with me.


We already have a rest client in catalog/rest directory, you can take a look at it.
