### ISSUE TITLE
Manage dependencies using workspace.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#24]
Following #15 , we should provide workspace wide dependency management.

**Comment by liurenjie1024** [comment]
We'll do this after #78 get merged.

**Comment by Xuanwo** [comment]
> Following #15 , we should provide workspace wide dependency management.

From my daily routine, I find it inconvenient when a library has workspace-wide dependencies. I have to read an extra file to know which version I'm depending on.

**Comment by liurenjie1024** [comment]
> > Following #15 , we should provide workspace wide dependency management.
> 
> From my daily routine, I find it inconvenient when a library has workspace-wide dependencies. I have to read an extra file to know which version I'm depending on.

But it makes dependencies of a crate easier to synchronize. cc @JanKaul @ZENOTME @Fokko What do you think?
