### ISSUE TITLE
Bug: No associated function values.rs // DateTime::from_timestamp_micros

### ISSUE THREAD

**Issue by marvinlanhenke** [apache/iceberg-rust#240]
I just merged main into my dev_branch - now, I cannot compile - perhaps its on my side, since i am not sure how this could slip through CI?

https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/spec/values.rs#L1589

error[E0599]: no function or associated item named `from_timestamp_micros` found for struct `DateTime` in the current scope
    --> crates/iceberg/src/spec/values.rs:1589:19
     |
1589 |         DateTime::from_timestamp_micros(micros).unwrap().naive_utc()
     |                   ^^^^^^^^^^^^^^^^^^^^^
     |                   |
     |                   function or associated item not found in `DateTime<_>`
     |                   help: there is a method with a similar name: `timestamp_micros`

**Comment by marvinlanhenke** [comment]
@liurenjie1024 
I think this was the commit that introduced the change? https://github.com/apache/iceberg-rust/commit/f61d47509e95b692f01fca23c53ff04349ed8849

**Comment by liurenjie1024** [comment]
> @liurenjie1024 
> 
> I think this was the commit that introduced the change? https://github.com/apache/iceberg-rust/commit/f61d47509e95b692f01fca23c53ff04349ed8849

Do you have Cargo.lock in your local env? You need to remove Caego.lock to upgrade dependencies automatically.

**Comment by marvinlanhenke** [comment]
> > @liurenjie1024
> > I think this was the commit that introduced the change? [f61d475](https://github.com/apache/iceberg-rust/commit/f61d47509e95b692f01fca23c53ff04349ed8849)
> 
> Do you have Cargo.lock in your local env? You need to remove Caego.lock to upgrade dependencies automatically.

thanks a lot this was it - issues is resolved
