### ISSUE TITLE
Integrate with datafusion

### ISSUE THREAD

**Issue by ZENOTME** [apache/iceberg-rust#242]
After support basic scan and catalog, we can consider to integrate with datafusion to speed up data driven tests.

**Comment by ZENOTME** [comment]
I'm working the draft so that we can have more clear discussion above it. Blocked by #277 now.

**Comment by marvinlanhenke** [comment]
@ZENOTME 
I'm interested in your approach, perhaps you can outline what you are going to do (high-level). I'm just curious and want to understand / research where those integrations points / interfaces might be? Thanks in advance and best regards.

**Comment by ZENOTME** [comment]
Thanks for raising this discussion @marvinlanhenke! The basic idea for the integration is to provide the wrap struct using type in iceberg-rust so that users can use them to connect with datafusion directly. 

## Implementation outline

### 1. Implement trait for managing the iceberg table.

The datafusion provides the following trait to manage the table:
- CatalogProviderList
- CatalogProvider
- SchemaProvider
- TableProvider

We can map them into the type in iceberg-rs
- CatalogProviderList: Maybe we don't need to implement this
- CatalogProvider: Catalog in iceberg-rust
- SchemaProvider: Namespace in iceberg-rust
- TableProvider: Table in iceberg-rust

We can implement them by wrapping using type in iceberg-rs internally. 

Like 
```
struct IcebergCatalogProvider {
  inner: iceberg_rs::Catalog
}

impl CatalogProvider for IcebergCatalogProvider {
  ...
}
```

### 2. Implement the trait for scanning the table.

And we also need to implement an ExecutionPlan for [scan in TableProvider](https://docs.rs/datafusion/latest/datafusion/datasource/provider/trait.TableProvider.html#tymethod.scan). This part we can rely on [TableScan in iceberg-rs](https://github.com/apache/iceberg-rust/blob/39aafdd2ea69968213e94534b5864fd595a6034a/crates/iceberg/src/scan.rs#L186)

Feel free to any suggestions and if something can be improved. Please let me know if there is something confusing.

**Comment by marvinlanhenke** [comment]
> The datafusion provides the following trait to manage the table:
> 
> * CatalogProviderList
> * CatalogProvider
> * SchemaProvider
> * TableProvider

Thank you so much for taking the time and making the effort to outline the approach. 

I just was looking for those traits you mentioned.
The rest is basically (over-simplified) just providing an Adapter, which is reasonable and easy to understand.

Thanks again.

**Comment by Xuanwo** [comment]
Basic integration has been added in https://github.com/apache/iceberg-rust/pull/324.

We can create a new tracking issues for missing pieces.
