### ISSUE TITLE
Loading table from metadata file directly.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#246]
This feature is quite similar to [StaticTable](https://github.com/apache/iceberg-python/blob/ea9da8856a686eaeda0d5c2be78d5e3102b67c44/pyiceberg/table/__init__.py#L574) in python api, which allows user to  load table without catalog.

**Comment by liurenjie1024** [comment]
Hi, @a-agmon 

I think both method could be provided and the second version could be implemented as a simple wrapper as the first one.

What I want to add is that instead of implement it directly on `Table`, I want to add a new struct `StaticTable` as following:

```rust
pub struct StaticTable(Table);

impl StaticTable {
 pub async fn from_metadata(metadata_file_location: &str, file_io: FileIO) -> anyhow::Result<Self> {
   ...
 }

   pub fn scan(&self) -> TableScanBuilder<'_> {
        TableScanBuilder::new(self.0)
    }

   pub fn metadata(&self) -> TableMetadataRef {...}
}
```

The reason we need a `StaticTable` is that it's readoly and mainly used for scan. With this approach we can forbid applying transaction on `StaticTable` in a type safe approach. What do you think?

**Comment by a-agmon** [comment]
Thanks @liurenjie1024 
Sounds good to me.

**Comment by a-agmon** [comment]
Hi @liurenjie1024 , 
Please take a look at the [PR](https://github.com/apache/iceberg-rust/pull/259) 
How does this look?

**Comment by liurenjie1024** [comment]
Hi, @a-agmon I've reviewed the pr and it looks great! I've left small comments to improve it.

**Comment by Xuanwo** [comment]
From the discussion: https://apache-iceberg.slack.com/archives/C05HTENMJG4/p1710392414486259

> The reason we need StaticTable Is that we don't want to allow modidication on tables loaded directly from metadata.

Should simply returning an error for modification operations be acceptable?

**Comment by liurenjie1024** [comment]
> Should simply returning an error for modification operations be acceptable?

Yeah, that's one approach. But The motivation behind Is that we want to do it in a type safe way without runtime check.

**Comment by Xuanwo** [comment]
> But The motivation behind Is that we want to do it in a type safe way without runtime check.

Do you think it's a good idea to provide both ways?

**Comment by liurenjie1024** [comment]
> > But The motivation behind Is that we want to do it in a type safe way without runtime check.
> 
> 
> 
> Do you think it's a good idea to provide both ways?

It's kind of weird to me to have both of them. Is there any concrete use case?

**Comment by Xuanwo** [comment]
> It's kind of weird to me to have both of them. Is there any concrete use case?

Database like databend supports loading iceberg table from both catalog and paths of a storage services.

For example:

```sql
CREATE TABLE <table_name> 
ENGINE = Iceberg 
LOCATION = 's3://<path_to_table>' 
CONNECTION_NAME = '<connection_name>'
```

If we provides `Table` and `StaticTable`, users will need to wrap them again like the following.

```rust
enum IcebergTable {
   Table(iceberg::Table),
   StaticTable(iceberg::StaticTable)
}
```

**Comment by a-agmon** [comment]
Perhaps we can also implement `from_metadata_file()` on `Table`? or provide an accessor to `Table` from `StaticTable` with some warning on usage?

**Comment by liurenjie1024** [comment]
> > It's kind of weird to me to have both of them. Is there any concrete use case?
> 
> 
> 
> Database like databend supports loading iceberg table from both catalog or paths of a storage services.
> 
> 
> 
> For example:
> 
> 
> 
> ```sql
> 
> CREATE TABLE <table_name> 
> 
> ENGINE = Iceberg 
> 
> LOCATION = 's3://<path_to_table>' 
> 
> CONNECTION_NAME = '<connection_name>'
> 
> ```
> 
> 
> 
> If we provides `Table` and `StaticTable`, users will need to wrap them again like the following.
> 
> 
> 
> ```rust
> 
> enum IcebergTable {
> 
>    Table(iceberg::Table), // build from catalog
> 
>    StaticTable(iceberg::StaticTable) // build from a path of table metadata
> 
> }
> 
> ```

Make sense. Will following code work for you?

```
struct Table <const N: bool>{}
```

**Comment by liurenjie1024** [comment]
> Perhaps we can also implement `from_metadata_file()` on `Table`? or provide an accessor to `Table` from `StaticTable` with some warning on usage? 

Good point, how about allowing access inner Table as unsafe?

**Comment by liurenjie1024** [comment]
If that still not works for you, I agree that we provide both apis.

**Comment by Xuanwo** [comment]
> Good point, how about allowing access inner Table as unsafe?

Providing a `StaticTable::into_table()` should work fine to me.

Alought I still stick with my idea that `Table` should be able to build without catalog and perform runtime checks againest `read_only` status. Maybe we can hide this under a feature for user?

By the way, `unsafe` is preserved for memory safe in rust. It doesn't make sense to mark the access to inner table as `unsafe`.

**Comment by liurenjie1024** [comment]
> Alought I still stick with my idea that Table should be able to build without catalog and perform runtime checks againest read_only status, returning errors if user tried to write. Maybe we can hide this under a feature for user?

How about this:

1. We add a readonly field in Table

2. When it load from catalog, readonly Is false 

3. We keep StaticTable so that user have a type safe readonly table 

4. Add into method for StaticTable   to get inner Table, and this case We set readonly to true

**Comment by a-agmon** [comment]
Maybe we can also incorporate something like this at this stage. like adding a _readonly_ property that will default to false, while the StaticTable sets it as true.

```rust
/// Table represents a table in the catalog.
#[derive(TypedBuilder, Debug)]
pub struct Table {
    file_io: FileIO,
    #[builder(default, setter(strip_option, into))]
    metadata_location: Option<String>,
    #[builder(setter(into))]
    metadata: TableMetadataRef,
    identifier: TableIdent,
    #[builder(default = false)]
    readonly: bool,
}
```
I tried to sketch it [here](https://github.com/a-agmon/iceberg-rust/blob/feat-add-static-table-2/crates/iceberg/src/table.rs) for example. I can add this if that seems right.

**Comment by liurenjie1024** [comment]
> Maybe we can also incorporate something like this at this stage. like adding a _readonly_ property that will default to false, while the StaticTable sets it as true.
> 
> 
> 
> ```rust
> 
> /// Table represents a table in the catalog.
> 
> #[derive(TypedBuilder, Debug)]
> 
> pub struct Table {
> 
>     file_io: FileIO,
> 
>     #[builder(default, setter(strip_option, into))]
> 
>     metadata_location: Option<String>,
> 
>     #[builder(setter(into))]
> 
>     metadata: TableMetadataRef,
> 
>     identifier: TableIdent,
> 
>     #[builder(default = false)]
> 
>     readonly: bool,
> 
> }
> 
> ```
> 
> I tried to sketch it [here](https://github.com/a-agmon/iceberg-rust/blob/feat-add-static-table-2/crates/iceberg/src/table.rs) for example. I can add this if that seems right.

Looks reasonably to me, thanks for  this!

**Comment by a-agmon** [comment]
> > Maybe we can also incorporate something like this at this stage. like adding a _readonly_ property that will default to false, while the StaticTable sets it as true.
> > ```rust
> > /// Table represents a table in the catalog.
> > 
> > #[derive(TypedBuilder, Debug)]
> > 
> > pub struct Table {
> > 
> >     file_io: FileIO,
> > 
> >     #[builder(default, setter(strip_option, into))]
> > 
> >     metadata_location: Option<String>,
> > 
> >     #[builder(setter(into))]
> > 
> >     metadata: TableMetadataRef,
> > 
> >     identifier: TableIdent,
> > 
> >     #[builder(default = false)]
> > 
> >     readonly: bool,
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried to sketch it [here](https://github.com/a-agmon/iceberg-rust/blob/feat-add-static-table-2/crates/iceberg/src/table.rs) for example. I can add this if that seems right.
> 
> Looks reasonably to me, thanks for this!

Great! PR is now also updated with changes.

**Comment by liurenjie1024** [comment]
Close by #259 Feel free to open when if necessary.
