### ISSUE TITLE
Implement `PruneColumns` for `Schema`.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#251]
See [java implementation](https://github.com/apache/iceberg/blob/c07f2aabc0a1d02f068ecf1514d2479c0fbdd3b0/api/src/main/java/org/apache/iceberg/types/PruneColumns.java#L42).

It's useful in schema projection, id projection.

**Comment by Dysprosium0626** [comment]
Hi @viirya @liurenjie1024 , Can I help with this issue and I have nearly completing implement `PruneColumn` for Schema.
See https://github.com/Dysprosium0626/iceberg-rust/commit/8295f83496a8cb60301cbbfa4c7432bb0ad49fd3. Currently I just need to add some test cases but I have no ideas(cuz it seems that there is no corresponding test cases in Java implementation).

**Comment by viirya** [comment]
Of course, yes. I plan to implement this but as you are close to finish it. I can help review once you submit the PR. 🙂

**Comment by Fokko** [comment]
If you are looking for tests, we have them on PyIceberg: https://github.com/apache/iceberg-python/blob/0ee7f1233e062b17b03fccc1eac6449c72e575f0/tests/test_schema.py#L564-L819

**Comment by liurenjie1024** [comment]
@Dysprosium0626 Yes, thanks!

**Comment by Dysprosium0626** [comment]
Hi @liurenjie1024, thanks for your review. This issue can be closed now.
