### ISSUE TITLE
Implement `ManifestEvaluator` to prune mainfest files.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#253]
See [python implementation](https://github.com/apache/iceberg-python/blob/4ed5a144ecad69878cf47292557b17df31ffe5a8/pyiceberg/expressions/visitors.py#L548)

Blocked by #264.

**Comment by waynexia** [comment]
I suppose this issue has been taken according to https://github.com/apache/iceberg-rust/pull/241#issuecomment-1987506207?

**Comment by liurenjie1024** [comment]
> I suppose this issue has been taken according to [#241 (comment)](https://github.com/apache/iceberg-rust/pull/241#issuecomment-1987506207)?

Not yet, there are some dependencies not implemented yet, I'll open issues and clarify their dependencies.

**Comment by marvinlanhenke** [comment]
@liurenjie1024 
Is it correct that we need to implement the `ProjectionEvaluator` beforehand in order to provide the `partition_filters`
and extend `TableScan` with row_filter: Predicate?

https://github.com/apache/iceberg-python/blob/4ed5a144ecad69878cf47292557b17df31ffe5a8/pyiceberg/table/__init__.py#L753-L763

**Comment by liurenjie1024** [comment]
> @liurenjie1024 Is it correct that we need to implement the `ProjectionEvaluator` beforehand in order to provide the `partition_filters` and extend `TableScan` with row_filter: Predicate?
> 
> https://github.com/apache/iceberg-python/blob/4ed5a144ecad69878cf47292557b17df31ffe5a8/pyiceberg/table/__init__.py#L753-L763

Yes, and before that we need to implement `project` for transform.

**Comment by marvinlanhenke** [comment]
I just browsed the issues, you've already listed the dependencies here: 
linking this for ref:
https://github.com/apache/iceberg-rust/issues/153

**Comment by liurenjie1024** [comment]
Close by #322
