### ISSUE TITLE
Support "prefix" prop in iceberg rest client

### ISSUE THREAD

**Issue by TennyZhuang** [apache/iceberg-rust#255]
This option is used by many hosted iceberg service.

https://github.com/apache/iceberg/blob/5c27843d77e19fa3eeb3472ee9dbc319566429dd/open-api/rest-catalog-open-api.yaml#L282

**Comment by TennyZhuang** [comment]
@liurenjie1024 Please assign the issue to me, thanks

**Comment by flyrain** [comment]
Assign this to you, @TennyZhuang. Thanks for taking a look at this.
