### ISSUE TITLE
Complete predicate builders for all operators.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#266]
See [example](https://github.com/apache/iceberg-rust/blob/0fc0b0f98ae1acf420b4537b27f5412ce887f8d1/crates/iceberg/src/expr/term.rs#L47). 
Add builder methods for left predicate operators with tests.

**Comment by QuakeWang** [comment]
I am interested in this issue, let me try it : )

**Comment by liurenjie1024** [comment]
> I am interested in this issue, let me try it : )

@QuakeWang Thanks, welcome to contribute.
