### ISSUE TITLE
Discussion: How to handle S3 Config in Catalog

### ISSUE THREAD

**Issue by marvinlanhenke** [apache/iceberg-rust#273]
...perhaps I am missing something, but currently I prototype the HMS Catalog like: 
```rust
let metadata = TableMetadataBuilder::from_table_creation(creation)?.build()?;
let metadata_location = get_metadata_location(&location, 0)?;

let file_io = FileIOBuilder::new("s3a")
    .with_props(vec![
        (S3_ENDPOINT, "http://0.0.0.0:9000".to_string()),
        (S3_ACCESS_KEY_ID, "minioadmin".to_string()),
        (S3_SECRET_ACCESS_KEY, "minioadmin".to_string()),
        (S3_REGION, "us-east-1".to_string()),
    ])
    .build()?;
let mut file = file_io.new_output(&metadata_location)?.writer().await?;
file.write_all(&serde_json::to_vec(&metadata)?).await?;
file.shutdown().await?;
```

@liurenjie1024 @Xuanwo 
Has there been any discussions or thoughts about where to set those configuration params? 
Currently I don't see anything setup - but I might be missing something?

One way to handle this would be to pass the params (or even the complete FileIO) into the `HmsCatalogConfig`?

```rust
pub struct HmsCatalogConfig {
    address: String,
    thrift_transport: HmsThriftTransport,
}

struct HmsClient(ThriftHiveMetastoreClient);

/// Hive metastore Catalog.
pub struct HmsCatalog {
    config: HmsCatalogConfig,
    client: HmsClient,
}
```

**Comment by odysa** [comment]
We may use a Hashmap for properties like the [RestCatalogConfig](https://github.com/apache/iceberg-rust/blob/6e29ca77fb48ea1c862efc325de93c15ea064c01/crates/catalog/rest/src/catalog.rs#L50) and [load_file_io](https://github.com/apache/iceberg-rust/blob/6e29ca77fb48ea1c862efc325de93c15ea064c01/crates/catalog/rest/src/catalog.rs#L528)

```rust
pub struct HmsCatalogConfig {
    address: String,
    thrift_transport: HmsThriftTransport,
	props: Hashmap<String, String>
}

let file_io = FileIO::from_path(url)?.with_props(config.props).build()?
```

**Comment by marvinlanhenke** [comment]
@odysa @Xuanwo 
this is the way I implemented it for now - and I think its fine. PR will be up for review once #271 has been resolved.
thanks again for your feedback.

**Comment by liurenjie1024** [comment]
@marvinlanhenke Sorry for late reply. I think this approach is fine, and java/python also follows this approach.
