### ISSUE TITLE
Implement transforms projection

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-rust#289]
For evaluating the hibben partition filters, we need to have column projections. For example, this will translate `dt <= 2024-02-01 and dt < 2024-03-01` to the partition filter `month(dt) = 2024-02`.

- The visitor: https://github.com/apache/iceberg-python/blob/bbc7e7c8d095b4afea5c27e6de324d008aa2d803/pyiceberg/expressions/visitors.py#L794-L854
- And we need to port the `project()` method from the transforms: https://github.com/apache/iceberg-python/blob/main/pyiceberg/transforms.py
- Last, but most importantly, we need to port a ton of tests to make sure that this is implemented correctly: https://github.com/apache/iceberg-python/blob/main/tests/test_transforms.py

**Comment by marvinlanhenke** [comment]
#264 as ref for implementing `project()`

**Comment by viirya** [comment]
Does this duplicate to #264?

**Comment by viirya** [comment]
If not, I will work on this.

**Comment by liurenjie1024** [comment]
I think this issue includes several things, and are tracked in https://github.com/apache/iceberg-rust/issues/153 .

**Comment by viirya** [comment]
> And we need to port the project() method from the transforms

For this one, it looks like the same as #264.

**Comment by liurenjie1024** [comment]
> > And we need to port the project() method from the transforms
> 
> For this one, it looks like the same as #264.

Exactly, #264 is blocked by #283 , and @ZENOTME has a pr for it.

**Comment by marvinlanhenke** [comment]
can this be closed - due to being a duplicate to #264 which was closed by #309?
