### ISSUE TITLE
Consider renaming `data_file` field  on FileScanTask to maintain consistency and  avoid confusion

### ISSUE THREAD

**Issue by a-agmon** [apache/iceberg-rust#299]
I have been running some tests with the TableScan API, and I think that there is something a bit puzzling about naming and access there. 

1. `TableScanBuilder`'s `build()` returns a `TableScan`. 
2. `TableScan`'s `plan_files()` returns a stream of `FileScanTask`

so far so good...

3. `FileScanTask` has a field named `data_file`, but that field doesn't return `DataFile`. Rather, it returns a `ManifestEntry` ([see here](https://github.com/apache/iceberg-rust/blame/fd9aa71193b68a48f7b082c49166203c0c8ff413/crates/iceberg/src/scan.rs#L201)). 
4. `ManifestEntry` also has a field named data_file, which does return an actual `DataFile` type, but it does not expose it ([see here](https://github.com/apache/iceberg-rust/blob/fd9aa71193b68a48f7b082c49166203c0c8ff413/crates/iceberg/src/spec/manifest.rs#L841)). `ManifestEntry` only exposes some of `DataFile` fields via public methods. 

Therefore, I think there are 2 issues here:
1. Because we do have a `DataFile` type, I think its confusing that `FileScanTask` has a field named `data_file`, which returns a `ManifestEntry` rather than a `DataFile`.
2. The `DataFile` fields and methods are public but are not effectively accessible via `TableScan`, because `ManifestEntry` "hides" `DataFile` itself.

It seems that the original design was based on the idea that `ManifestEntry` should encapsulate and hide DataFile. If we want to address this, I think we have 2 choices here:  The less optimal choice, in my view, is to follow this encapsulation logic and only expose `DataFile` fields via public methods on `ManifestEntry`.

The other option, is to rename the `data_file` field on FileScanTask to `manifest_entry` whereas the data file fields will be accessed like: `file_scan_task.manifest_entry().data_file().some_property`

I have a small PR that shows the latter suggestion. Please let me know if this sounds like a good direction and I will post it for your consideration

**Comment by marvinlanhenke** [comment]
> The other option, is to rename the `data_file` field on FileScanTask to `manifest_entry` whereas the data file fields will be accessed like: `file_scan_task.manifest_entry().data_file().some_property`

This makes the most sense to me.

**Comment by liurenjie1024** [comment]
Hi, @a-agmon Thanks for raising this. Let me add some background here, the reason the field is named as `data_file` is that, in fact for each `FileScanTask` we have not only data, but also deletion tasks, e.g. position deletes and eq delete files. Currently they are not included because the logic of applying and pruning deletion files is a little complicated, and we  
decided to focus on read only data first. 

> The other option, is to rename the data_file field on FileScanTask to manifest_entry whereas the data file fields will be accessed like: file_scan_task.manifest_entry().data_file().some_property

This is reasonable to me, but I have a small suggestion to rename `data_file` to `data_manifest_entry`, what do you think?

**Comment by marvinlanhenke** [comment]
> This is reasonable to me, but I have a small suggestion to rename `data_file` to `data_manifest_entry`, what do you think?

Can we not simply use `manifest_entry` instead of data_file and have the delete_file named explicitly like that, once we get there? I think this is how the java impl does it (I only took a quick look - so bear with me if I'm mistaken)? https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/FileScanTask.java

**Comment by liurenjie1024** [comment]
> > This is reasonable to me, but I have a small suggestion to rename `data_file` to `data_manifest_entry`, what do you think?
> 
> Can we not simply use `manifest_entry` instead of data_file and have the delete_file named explicitly like that, once we get there? I think this is how the java impl does it (I only took a quick look - so bear with me if I'm mistaken)? https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/iceberg/FileScanTask.java

Sorry I don't quite get your meaning, do you mean to use `manifest_entry` for data file, and `deletes` for deletions?

**Comment by a-agmon** [comment]
> Hi, @a-agmon Thanks for raising this. Let me add some background here, the reason the field is named as `data_file` is that, in fact for each `FileScanTask` we have not only data file, but also deletion files, e.g. position deletes and eq delete files. Currently they are not included because the logic of applying and pruning deletion files is a little complicated, and we decided to focus on read only data first.
> 
> > The other option, is to rename the data_file field on FileScanTask to manifest_entry whereas the data file fields will be accessed like: file_scan_task.manifest_entry().data_file().some_property
> 
> This is reasonable to me, but I have a small suggestion to rename `data_file` to `data_manifest_entry`, what do you think?

Sounds good. Will submit a PR for us to consider.

**Comment by a-agmon** [comment]
Hi, 
Please see this PR and let me know what do you think
https://github.com/apache/iceberg-rust/pull/300

**Comment by a-agmon** [comment]
> > Sorry I don't quite get your meaning, do you mean to use `manifest_entry` for data file, and `deletes` for deletions?
> 
> Yes. Something like that.

Not sure if that is what you mean, but `DataFile` has a content field which is basically an enum that indicates whether its Data, PositionDeletes or EqualityDeletes
so that can be accessed via `data_manifest_entry.data_file().content()`
