### ISSUE TITLE
Bug: `fn day_timestamp_micro` produces wrong results

### ISSUE THREAD

**Issue by marvinlanhenke** [apache/iceberg-rust#311]
### Description:
`fn day_timestamp_micro` ([source](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/transform/temporal.rs#L167)) seems to produce the wrong result which is off-by-one due to rounding errors.
Also the implementation does not align with the [Java ](https://github.com/apache/iceberg/blob/d350c9b8c995a2953aa8b80a0a1fc7cadc4dd16a/api/src/main/java/org/apache/iceberg/util/DateTimeUtil.java#L174-L184C7)implementation, which handles the conversion slightly different.

An example of the wrong output can be seen in the [test](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/transform/temporal.rs#L587):
`-115200000000` evaluates to `1969-12-30T16:00:00Z` which should be days -2 (since epoch) and not -1.

### Proposal:
Align Rust with Java implementation.
I already have a prototype, due to working on #264, so I will implement the fix in a different PR - so it can be verified more easily.

**Comment by marvinlanhenke** [comment]
cc @liurenjie1024 
Prototype for the fix can be seen in #309, however I still have to handle unwrap and change the return type to `Result<i32>`. This should be enough, however, to verify if the logic is correct.

**Comment by liurenjie1024** [comment]
Hi, @marvinlanhenke Thanks for the debug, yes we should align with java/python implementation carefully.

**Comment by liurenjie1024** [comment]
Do you mind to submit a pr to fix it?

**Comment by marvinlanhenke** [comment]
@liurenjie1024
I'll try to get to submit a PR this evening. Still need to handle unwrap properly.

**Comment by marvinlanhenke** [comment]
@liurenjie1024 
...while looking at it - I think we need to handle `Year, Month, and Hours` as well? The Java implementation does the same thing for all granularities.

**Comment by liurenjie1024** [comment]
> @liurenjie1024 ...while looking at it - I think we need to handle `Year, Month, and Hours` as well? The Java implementation does the same thing for all granularities.

Yes, exactly.
