### ISSUE TITLE
CI-Build: Breaks due to `motore` update

### ISSUE THREAD

**Issue by marvinlanhenke** [apache/iceberg-rust#315]
> error: package `motore-macros v0.4.1` cannot be built because it requires rustc 1.77.0 or newer, while the currently active rustc version is 1.75.0
> Either upgrade to rustc 1.77.0 or newer, or use
> cargo update motore-macros@0.4.1 --precise ver
> where `ver` is the latest version of `motore-macros` supporting rustc 1.75.0
> Error: Process completed with exit code 101.

...I think this comes from the transitive dependency defined by "[volo-thrift](https://crates.io/crates/volo-thrift/0.9.2/dependencies)", which specifies `motore = ^0.4` ...motore had an update 4 hours ago to ver 0.4.1 which seems to break the CI.

I'm not sure what's the best approach here. Upgrade the rust-version? Running `cargo update motore-macros@0.4.0 --precise 0.4.0` fixes the build  locally.

**Comment by marvinlanhenke** [comment]
cc @liurenjie1024 @Xuanwo

**Comment by liurenjie1024** [comment]
I'm in favor of updating rustc since we want to use latest `volo-thrift`, the only cons is that it requires users to upgrade rustc to 1.77.0+.

> Running cargo update motore-macros@0.4.0 --precise 0.4.0 fixes the build locally.

This is in fact pinning motore to some old version, but I guess we will eventually need latest feature.
