### ISSUE TITLE
Add transform function implementation.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#32]

**Comment by liurenjie1024** [comment]
Blocked by #38

**Comment by liurenjie1024** [comment]
From our experience in developing https://github.com/icelake-io/icelake, we should implement it on arrow array when introducing partition writer.

cc @ZENOTME  Coule you help to port our implementation here later?

**Comment by ZENOTME** [comment]
> cc @ZENOTME Coule you help to port our implementation here later?

Sure. I'm implementing the transform function for temporal type in icelake now. I will port them gradually later.

**Comment by liurenjie1024** [comment]
> Regarding the representation of partition values which relates to the use of transform. I'm wondering whether the result of a transform should be a scalar value. There should only be one partition value for each partition which is stored in the datafile. And the partition values are not written to disk.

Yeah, I can understand that it's a little difficult to understand why we should implement on arrow. I will use a simplified partition writer to explain this:
```rust
struct PartitionWriter {
  transform_func: Box<dyn TransformFunction>,
  parquet_writers: HashMap<PartitionValue, ParquetWriter>
}

impl PartitionWriter {
  fn append(record_batch: RecordBatch)  {
     let partition_values = transform_func.apply(record_batch.get(0)).map(|arrow_row| to_iceberg_partition_value(arrow_row))?; // We assume partition function should apply on the first column
    
     for i in 0..record_batch.row_count() {
      parquet_writers.get(partition_values.get(i)).append(record_batch.rows(i));
}
     
  }
}
```

With this approach, we can compute partiton values in a vectorized approach. For more detailed implementation, please refer to  https://github.com/icelake-io/icelake/blob/aeba46c62932b482340d34550289a1b3a9f30486/icelake/src/io/task_writer.rs#L175

**Comment by JanKaul** [comment]
Ah okay, thanks for the explanation. So the reason is to "multiplex" the rows into the correct parquet writer according to its partition value.

Do you think it's possible to use the capabilities of the query engine to repartition the data? Maybe there are some optimizations that can be performed if this is expressed as an Repartition Operator.

**Comment by ZENOTME** [comment]
> Do you think it's possible to use the capabilities of the query engine to repartition the data? May be there are some optimizations that can be performed if this is expressed as an Repartition Operator.

Good point! In icelake, the repartition work is doing by HashMap and arrow provide [the effiect way](https://docs.rs/arrow-row/46.0.0/arrow_row/index.html) to hash the partition value. And as you says this work maybe can express as [Repartition Operator](https://arrow.apache.org/datafusion/user-guide/dataframe.html#:~:text=Repartition%20a%20DataFrame%20based%20on%20a%20logical%20partitioning%20scheme.). We can take the investigate.

**Comment by liurenjie1024** [comment]
> Do you think it's possible to use the capabilities of the query engine to repartition the data? Maybe there are some optimizations that can be performed if this is expressed as an Repartition Operator.

Yeah, it's possible. However, usually we don't bind compute task to one partition of storage format, since the parallelism of of compute tasks is determined by many factors, not just table partition. I think the hierarchy of iceberg's `TaskWriter` explains things well enough:

<img width="461" alt="image" src="https://github.com/apache/iceberg-rust/assets/2771941/f8fb3128-d22f-4e0b-80c0-9592f075e748">

`PartitionedWriter` is used when data is partitioned and sorted according to partition value.

`PartitionedFanoutWriter` is used when data not partitioned by shuffle, and need to be precessed in writer.

**Comment by JanKaul** [comment]
That makes sense. Thanks again for the explanation.

Generally it makes sense to have a PartitionWriter that doesn't depend on a query engine. Then this could be used in other libraries.

**Comment by liurenjie1024** [comment]
Close since already finished.
