### ISSUE TITLE
Allow conversion between literal values

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-rust#33]
I noticed the following: https://github.com/apache/iceberg-rust/pull/29/files#diff-a129ecbb5292628eaa22ebd56d7e869efaaf05f27646c7e724a205b4564505abR745

```rust
Uuid::parse_str("0db3e2a8-9d1d-42b9-aa7b-74ebe558dceb").unwrap()
```

I would do a suggestion here that we're using in PyIceberg and that works very well.

```python
literal("0db3e2a8-9d1d-42b9-aa7b-74ebe558dceb").to(UuidType())
literal("true").to(BooleanType())
literal("2017-08-18"), DateType()
```

Where the `literal("true")` produces a `StringLiteral`, and then we can convert it to different literal types. 

It also works when starting from other types:
```python
literal(34).to(FloatType())
# Days since 1970-01-01
literal(12345).to(DateType())
```

This way we can accept any value, and when binding it to a field, convert it to the correct type. This works very well in Java and PyIceberg when accepting an expression `timestamp >= '2021-01-01'` where the date is first a string, and then we can convert this to the type of `timestamp` when binding it to the schema a timestamp in this case. Similarly, if the table has a `date(timestamp)` partition, we can convert it to a `DateType` to compare it to the partition. If the table would evolve its partitioning scheme from `date` to `hour`, we could just convert it to a `datetime` (miliseconds since epoch) and use this for the new partitioning scheme.

**Comment by liurenjie1024** [comment]
Good suggestion! I will take a look at python's code and try to implement it.
