### ISSUE TITLE
Update Roadmap / Close old Issues

### ISSUE THREAD

**Issue by marvinlanhenke** [apache/iceberg-rust#330]
I think we should update the roadmap, which I believe is really helpful not only to provide a general direction but also to attract more contributors. Also we have some 'older' issues that seem to be already done - or not relevant anymore. Perhaps we can do some grooming here (I'd be happy to help).

**Comment by marvinlanhenke** [comment]
cc @liurenjie1024

**Comment by liurenjie1024** [comment]
@marvinlanhenke Sorry for late reply. Yeah I think we should update the roadmap to reflect latest update, welcome to submit pr, thanks!

**Comment by liurenjie1024** [comment]
cc @marvinlanhenke Could we close this now?

**Comment by marvinlanhenke** [comment]
@liurenjie1024
regarding the roadmap i think we can close this, however perhaps we want to do some grooming and close some old issues as well - or maybe duplicates. I think you have a better overview if its worth the effort?
