### ISSUE TITLE
Read ManifestList, Manifest

### ISSUE THREAD

**Issue by ZENOTME** [apache/iceberg-rust#36]
For ManifestList, Manifest, I think #29 already as a good example to refer. We can define a unified view in memory and distinguish version1 and version2 in representation for serde.

And for the representation in memory, we can refer [icelake](https://github.com/icelake-io/icelake/blob/393d000f2e952bd32045da87a0d06d66047278f0/icelake/src/types/in_memory.rs#L905).

**Comment by ZENOTME** [comment]
I'm glad to prepare PR for it.

**Comment by JanKaul** [comment]
Thanks for taking this on!

There is one issue with the upper & lower bounds. The upper and lower bounds are stored as bytes, which can only be interpreted with the schema. So we will not be able to deserialize directly into the unified view. There needs to be a function which takes the schema into account.

Alternatively we could store the bytes in the unified view, but I think that's not the way to go.

Serialization should be fine.

**Comment by liurenjie1024** [comment]
Maybe we should complete #37 first.

**Comment by ZENOTME** [comment]
> There is one issue with the upper & lower bounds. The upper and lower bounds are stored as bytes, which can only be interpreted with the schema. So we will not be able to deserialize directly into the unified view. There needs to be a function which takes the schema into account.

> Alternatively we could store the bytes in the unified view, but I think that's not the way to go.

Yes, I agree with you. Maybe we can store the bytes in representation of serde first. And then take the schema to interpreted them to unified view in memory.

**Comment by JanKaul** [comment]
You could deserialize into `serde_bytes::ByteBuf` and then use [Literal::try_from_bytes](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/spec/values.rs#L267C12-L267C26).

**Comment by Fokko** [comment]
> There is one issue with the upper & lower bounds. The upper and lower bounds are stored as bytes, which can only be interpreted with the schema. So we will not be able to deserialize directly into the unified view. There needs to be a function which takes the schema into account.

In other languages, we keep this as bytes before deserialization. The metrics can become quite large and therefore become pretty expensive.

**Comment by liurenjie1024** [comment]
Close by #79
