### ISSUE TITLE
Allow Schema struct serialization/de-serialization

### ISSUE THREAD

**Issue by y0psolo** [apache/iceberg-rust#41]
Hi,

I am trying to implement the catalog API call with your models. Some of the API call rely on serializing Schema directly without encapsulating it inside a TableMetadata struct (for example CreateTableRequest inside https://github.com/apache/iceberg/blob/master/open-api/rest-catalog-open-api.yaml).
Unfortunately SchemaV1 or SchemaV2 is not public and Schema, which is public, is not currently serializable/de-serializable.
I wrote a small adaptation [here](https://github.com/y0psolo/iceberg-rust) to allow Schema serialization/de-serialization based on how it was implemented for TableMetadata struct. It seems to work, at least for me.

Do you want i submit a pull request or do you see other ways of achieving the Schema struct serialization/de-serialization ?

Thanks

**Comment by liurenjie1024** [comment]
Hi, @y0psolo Thanks for the interests. About catalog api, I think we should design the interface before actually implementing it. 
To serialize schema, the `SchemaV1`/`SchemaV2` are made private on purpose, to serialize it I think it's better to expose some functions such as `fn serialize_schema_in_v1_json` etc.

**Comment by Xuanwo** [comment]
Apologies for the delay in addressing https://github.com/apache/iceberg-rust/issues/23. I will work on resolving this issue promptly.

**Comment by JanKaul** [comment]
Regarding the serialization/serialization of Schema. I think I could implement `Serialize,Deserialize` for schema based on `into` and `try_from`. I will try to work on it in the next couple of days.

**Comment by y0psolo** [comment]
Hi

Thanks for your fast feedback.

@JanKaul i already did a try here https://github.com/y0psolo/iceberg-rust of Serialize, Deserialize implementation for Schema based on `into `and `try_fom` with test. Have a look it may save you some time (i am quite new to rust so be kind :) ). I can submit a pull request. 

@Xuanwo i never ever wanted to imply you are late. Sorry for that. It's open source project and i am more than happy than rust guys are giving some love to iceberg ... at their own pace.

**Comment by JanKaul** [comment]
Sorry @y0psolo, I should have looked at your code more thoroughly. I thought you wanted to make `SchemaV1,SchemaV2` public. 

Your code looks great! It would be great if you could create a PR. Thanks for working on this!

**Comment by liurenjie1024** [comment]
Should we close this now? cc @Fokko
