### ISSUE TITLE
discussion: Refactor our integration tests to make it more scalable.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#425]
## Background

Currenlty in our integration tests, for each test(each function), we will use docker compose to start a set of containers and stop them after tests done, see [this line](https://github.com/apache/iceberg-rust/blob/dcc380af294862b0a802b140c813b4cc4e304441/crates/catalog/glue/tests/glue_catalog_test.rs#L220) for an example. The advantage of this approach is that it provides perfect isolation for each test. But #420 shows that this may not be scalable on systems like macos.

## Proposal

Refactor our tests to what's in [pyiceberg](https://github.com/apache/iceberg-python/blob/ba296f6aef0c7fb1e29bc3c504a1af8a0af98ceb/Makefile#L41), e.g. we use scripts to start containers outside tests, tests only cares about actual logic.

The pros of this approach is that it scales better and supposed to run faster.

The cons of this approach is that developers need to be careful with namespace issues for each test, also simple `cargo test` no longer works well.

## Alternatives

There are some approaches to limit the concurrency of tests, for example `RUST_TEST_THREADS`, `--tests-threads`, etc. But they make the tests slower to execute.

**Comment by Xuanwo** [comment]
> The cons of this approach is that developers need to be careful with namespace issues for each test, also simple `cargo test` no longer works well.

I feel like we can implement our test harness by using [libtest_mimic](https://docs.rs/libtest-mimic) so `cargo test` can keep working.

Here is an example from opendal:

https://github.com/apache/opendal/blob/main/core/tests/behavior/main.rs#L54

```rust
fn main() -> anyhow::Result<()> {
    let args = Arguments::from_args();

    let mut tests = Vec::new();

    async_read::tests(&op, &mut tests);

    ...

    let conclusion = libtest_mimic::run(&args, tests);

    conclusion.exit()
}
```

**Comment by thexiay** [comment]
Maybe there is a way to balance the development experience and improve the performance of  preparing container environment.

E.g. [testcontainers, factory.rs](https://github.com/testcontainers/testcontainers-rs/blob/main/testcontainers/src/core/client/factory.rs), you can init docker compose once and reuse it in multiple test case.

use `OnceLock<Mutex<Weak<DockerCompose>>>`  to slove problem, re-initialize it or reuse it when you get it, and return `Arc<DockerCompose>`, when all reference of `DockerCompose`, the `Drop` of `DockerCompose` will be called automatic.

**Comment by ZENOTME** [comment]
Thanks @thexiay . The solution looks good to me.

> This may not be a limitation for now, since most of our integration tests only have one file. But in future if we have more complex test, we may still need to refactor to adopt @Xuanwo 's solution.

I think it's still possible to share a var within multiple test files for the integration test within one crate.

**Comment by Xuanwo** [comment]
> Personally I'm in favor @thexiay 's solution since currently it doesn't limit us much. We may adopt @Xuanwo 's solution when necessary.

Well, I'm not a fan of running integration tests in IDE, so I don't care this part very much :laughing: 

I'm willing to help migrate our our test harness if decided.

**Comment by thexiay** [comment]
> It seems that currently all our crates's integration tests have only one file, so how about we get started with @thexiay 's simpler approach, and do the migration when necessary? cc @Xuanwo What do you think?

If you guys certain it, i can finish this approach and  integrate it into test_utils.

**Comment by Xuanwo** [comment]
> It seems that currently all our crates's integration tests have only one file, so how about we get started with @thexiay 's simpler approach, and do the migration when necessary? cc @Xuanwo What do you think?

That's fine with me. We can always improve this part as needed. So please feel free to dive in, @thexiay.
