### ISSUE TITLE
ci: Add macos runner for ci.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#436]
I just realized that github provided github runners for macos: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

It would be greate to add ci for macos since it's an important environment for developer.

**Comment by QuakeWang** [comment]
Please assign it to me : )

**Comment by QuakeWang** [comment]
> Hi, @QuakeWang I see that it's only enabled for build, I mean to have tests also enabled.

Okay, I get it~
