### ISSUE TITLE
Add `cargo machete` to check unused dependencies.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#439]
[cargo udeps](https://crates.io/crates/cargo-udeps) is a tool for discovering unused dependencies. It requires unstable rust to run, but I think it's ok to use unstable rust in ci.

**Comment by Xuanwo** [comment]
I will suggest to use [cargo-machete](https://github.com/bnjbvr/cargo-machete) for it's super fast speed.

**Comment by vaibhawvipul** [comment]
I can work on this if no one else if working on it.

**Comment by Xuanwo** [comment]
> I can work on this if no one else if working on it.

Thanks a lot! Have fun.
