### ISSUE TITLE
Discussion: Use unstable rust to run ci tool.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#440]
Currently iceberg-rust requires stable rust to build, which is reasonable as a library. But ci tools such as `cargo fmt`, `cargo clippy` are only used during ci or local development, and will not force downstream application/libary to use unstable rust. Some advanced features of these tools are only available in unstable rust, so I would propose to use unstable rust to run these tools.

**Comment by Xuanwo** [comment]
I propose using the exact same nightly toolchain date as the stable Rust release in our `rust-toolchain` file. For example, if Rust 1.79 is released on `2024-06-13`, we will use `nightly-2024-06-13` for our development toolchain.

So we will have the same code (nearly) as stable rust, but also allow us to use nightly options.
