### ISSUE TITLE
Use cargo-nextest to run tests.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#459]
[cargo-nextest](https://nexte.st/) provides better interface and faster execution speed to rust tests, we should move to it to improve developer experience.

**Comment by vivek378521** [comment]
Should this change be made on the CI, too? or just makefile?

I see in the nextest docs that docs-test isn't supported, the rest can be ported.

**Comment by vivek378521** [comment]
I have raised a PR for this change: https://github.com/apache/iceberg-rust/pull/464

Please review.

**Comment by Fokko** [comment]
Seems like `nextest` has some limitations, see https://github.com/apache/iceberg-rust/pull/464. I'll close this issue for now.
