### ISSUE TITLE
Discussion: Add Makefile or Justfile to make tasks easier.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#47]
1. Should we add a make file to group commands to improve developer experience?

I want to enter some commands such as `make check` to run fmt, clippy, tests together so that we don't need to run them one by one before submitting pr.

2. If we agree on 1, should we use makefile or justfile?

The advantage of makefile is that `make` command is ubiquitous.

The advantage of justfile is that [`just`](https://github.com/casey/just) command is more modern. But it requires developer to install it.

cc @JanKaul @Xuanwo @nastra @ZENOTME @Fokko Welcome comments

**Comment by JanKaul** [comment]
Good idea. I would prefer `make` since we don't have a very complicated setup and no dependencies have to be installed.

**Comment by Xuanwo** [comment]
I don't like using task runners like `make` or `just`. Running `cargo fmt` and `cargo clippy` is not a burdensome task. In the worst case scenario, we can simply submit a PR and address any failing tasks. This approach is sufficient as developers only need to fix the specific tasks that have failed, without requiring additional tool installations or usage.

However, adding a new task runner does not prevent me from using `cargo`. Therefore, I am open to the idea if someone wants it.

**Comment by ZENOTME** [comment]
> Good idea. I would prefer make since we don't have a very complicated setup and no dependencies have to be installed.

Agree. 

And according my recent experience in debug integration test, having a way to create integration enviroment quickly will make debug more happy. (Although not sure whether it appropriate to be placed in make.

**Comment by liurenjie1024** [comment]
Cool, let's go with make file.
