### ISSUE TITLE
Add memory support for file_io

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#477]
We can use an in-memory filesystem by default, eliminating the need to change the environment. 

I will build one for file_io.

_Originally posted by @Xuanwo in https://github.com/apache/iceberg-rust/pull/475#discussion_r1690038773_

**Comment by sdd** [comment]
I have a local branch where I've modified FileIO to add an OpenDAL `Layer` that does  in-memory caching of the underlying files using the `moka` crate. I can share the details if you think it might be helpful

**Comment by Xuanwo** [comment]
That's nice! Please share it to me :heart: 

By the way, opendal has native support of moka and mini_moka, maybe also useful for caching.
