### ISSUE TITLE
No builder for TableMetadata and no public field

### ISSUE THREAD

**Issue by y0psolo** [apache/iceberg-rust#52]
There is no way to create a new TableMetadata struct outside a deserialization operation. I don't know if it's intended but all other struct have either builder or public field.

By the way i dont see clearly a consistent way of building API struct. Sometimes there is a builder and no public field, sometimes public field and no builder and sometimes builder and public field.

To have a better visibility on this I could write, if you want, a short table summary if needed with all API struct and two column : pub  field (yes/no), builder (yes/no)

**Comment by liurenjie1024** [comment]
Hi, @y0psolo Thanks for the contribution. We had a discussion in #3 about the style of public api, in conclusion
1. For complex structs such as TableMetadata, Sanpshot, Schema, etc, we prefer not to expose pub field, but only necessary methods
2. I'm ok with builder pattern.

cc @Xuanwo @ZENOTME @JanKaul Any comments?

**Comment by JanKaul** [comment]
I would also be in favor of using the builder pattern for the pub structs.

If I'm correct all pub structs except for TableMetadata already have a builder. With the `derive_builder` crate it should be quite easy to implement the buider for TableMetadata.

**Comment by y0psolo** [comment]
i will try to start working on it next week. Not too much spare time till now.

**Comment by Fokko** [comment]
Now https://github.com/apache/iceberg-rust/pull/587 is in, I'll go ahead and close this issue 👍
