### ISSUE TITLE
Use `std::thread::available_parallelism` instead of `num_cpus`

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#525]
Not a reivew comment, just a glimpse of this PR, we can replace this with `std::thread::available_parallelism()`, `num_cpus` is almost unmaintained (as it no longer needs to), and has issues that are solved by the std counterpart, e.g., this one: [std::thread::available_parallelism() return 0](https://github.com/rust-lang/rust/issues/115868).

_Originally posted by @SteveLauC in https://github.com/apache/iceberg-rust/pull/373#discussion_r1706281350_

**Comment by SteveLauC** [comment]
Let me take this, looks pretty straightforward:)
