### ISSUE TITLE
FileIO S3: accept session_token

### ISSUE THREAD

**Issue by twuebi** [apache/iceberg-rust#528]
Currently, FileIO does not work with temporary credentials obtained via aws sts, this is likely due to it not accepting the session token:

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

> When you make a call using temporary security credentials, the call must include a session token, which is returned along with those temporary credentials. AWS uses the session token to validate the temporary security credentials.

The only accepted keys are:

```rust
/// Following are arguments for [s3 file io](https://py.iceberg.apache.org/configuration/#s3).
/// S3 endpoint.
pub const S3_ENDPOINT: &str = "s3.endpoint";
/// S3 access key id.
pub const S3_ACCESS_KEY_ID: &str = "s3.access-key-id";
/// S3 secret access key.
pub const S3_SECRET_ACCESS_KEY: &str = "s3.secret-access-key";
/// S3 region.
pub const S3_REGION: &str = "s3.region";
```

We should add support for `s3.session-token`.

**Comment by Xuanwo** [comment]
It's possible right now by using [session_token](https://docs.rs/opendal/latest/opendal/services/struct.S3Config.html#structfield.session_token)

**Comment by twuebi** [comment]
I created a PR #530
