### ISSUE TITLE
bug: Main branch build failed.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#563]
Seems that the deploy to github pages workflow failed. cc @Xuanwo

**Comment by Xuanwo** [comment]
It seems the infra team has changed "Workflow Permissions" in the Apache org. I have contact with them. This should have been fixed now, please try agaib.

**Comment by Xuanwo** [comment]
> It seems the infra team has changed "Workflow Permissions" in the Apache org. I have contact with them. This should have been fixed now, please try again.

Not fixed by them. I will address by ourselves.
