### ISSUE TITLE
bug: `highest_field_id` in schema should include nested fields.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#589]
Currently for a schema like following:

```
[
  foo (id: 1, type String),
  bar (id: 2, type Struct),
     | - baz (id: 3, type String)
     | - ban (id: 10, type Int)
]
```

The `highest_field_id` is calculated as 2 since we don't count nested field. It's supposed to be 10.

**Comment by Xuanwo** [comment]
Fixed by https://github.com/apache/iceberg-rust/pull/590
