### ISSUE TITLE
bug: Arrow map type should be List(Struct<k, v>) instead of Struct<k, v>

### ISSUE THREAD

**Issue by chenzl25** [apache/iceberg-rust#606]
The current conversion of map type between iceberg and arrow is Map(Struct<k, v>). However, by arrow definition, it should be Map(List(Struct<k, v>))
https://github.com/apache/iceberg-rust/blob/620d58e81f85858e01b0a2f81656425269061dbe/crates/iceberg/src/arrow/schema.rs#L497-L522

Arrow Map definition
> /// A Map is a logical nested type that is represented as
    ///
    /// `List<entries: Struct<key: K, value: V>>`
    ///
    /// The keys and values are each respectively contiguous.
    /// The key and value types are not constrained, but keys should be
    /// hashable and unique.
    /// Whether the keys are sorted can be set in the `bool` after the `Field`.
    ///
    /// In a field with Map type, the field has a child Struct field, which then
    /// has two children: key type and the second the value type. The names of the
    /// child fields may be respectively "entries", "key", and "value", but this is
    /// not enforced.

**Comment by xxchan** [comment]
> by arrow definition, it should be Map(List(Struct<k, v>))

🤔 IIUC the `field` in `DataType::Map(field)` is indeed a struct. (But I would agree arrow-rs's representation is confusing. Perhapts it should use a dedicated `StructType`)

Here's an example in arrow-rs's tests:

https://github.com/apache/arrow-rs/blob/0491294828a6480959ba3983355b415abbaf1174/arrow-array/src/array/map_array.rs#L514-L527

Map is a "logical type", i.e., it's physically equivalent to `List<Struct<K,V>>`

**Comment by chenzl25** [comment]
> > by arrow definition, it should be Map(List(Struct<k, v>))
> 
> 🤔 IIUC the `field` in `DataType::Map(field)` is indeed a struct. (But I would agree arrow-rs's representation is confusing. Perhapts it should use a dedicated `StructType`)
> 
> Here's an example in arrow-rs's tests:
> 
> https://github.com/apache/arrow-rs/blob/0491294828a6480959ba3983355b415abbaf1174/arrow-array/src/array/map_array.rs#L514-L527
> 
> Map is a "logical type", i.e., it's physically equivalent to `List<Struct<K,V>>`. `Map(List(Struct<k, v>))` would look strange.

oops, I am sorry about that. The current implementation is correct. Let me close this issue.
