### ISSUE TITLE
Bump arrow to 53

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#622]
- close https://github.com/apache/iceberg-rust/pull/621
- close https://github.com/apache/iceberg-rust/pull/620
- close https://github.com/apache/iceberg-rust/pull/619
- close https://github.com/apache/iceberg-rust/pull/618
- close https://github.com/apache/iceberg-rust/pull/617

**Comment by sdd** [comment]
I can pick this up.

**Comment by sdd** [comment]
This is blocked on DataFusion. The most recently released version of DataFusion, v41.0.0, depends on arrow-* 52.

Once https://github.com/apache/datafusion/pull/12032 is in a released version, we can proceed.
