### ISSUE TITLE
test: Replace binary avro file by generating it on the fly.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#70]
I think it is worth the effort to generate the files. This way we can also generate the whole structure later on (manifest-list, manifest, datafile). Since Iceberg requires absolute paths, it is not easy to generate these files on forehand (looking at the Windows CI 😁)

_Originally posted by @Fokko in https://github.com/apache/iceberg-rust/pull/56#discussion_r1338197094_

**Comment by barronw** [comment]
Hi @liurenjie1024. Can I work on this issue?

**Comment by liurenjie1024** [comment]
> Hi @liurenjie1024. Can I work on this issue?

Yes, sure. Thanks!

**Comment by liurenjie1024** [comment]
cc @barronw Are you still interested in this?

**Comment by barronw** [comment]
> cc @barronw Are you still interested in this?

Hi! I can get this a pull request out this week. If someone else wants to work on it in the meantime, feel free!

**Comment by liurenjie1024** [comment]
> > cc @barronw Are you still interested in this?
> 
> Hi! I can get a pull request out this week. If someone else wants to work on it in the meantime, feel free!

This is a blocker of our first release, so I will take this so that our release is not blocked.

**Comment by Fokko** [comment]
I would love to see this before the release, there is also some interesting data here: https://github.com/apache/iceberg-rust/pull/79#discussion_r1425129671
