### ISSUE TITLE
Manifest List Writer Design

### ISSUE THREAD

**Issue by barronw** [apache/iceberg-rust#72]
Hi! I'd like to review a design for a manifest list writer before implementation. The design is based on Icelake and PyIceberg.

```rust
struct ManifestListWriterV1 {
    output_file: OutputFile,
    snapshot_id: i64,
    parent_snapshot_id: i64,
}

impl ManifestListWriterV1 {
    fn new(
        output_file: OutputFile, 
        snapshot_id: i64, 
        parent_snapshot_id: i64
    ) -> ManifestListWriterV1 {
        ...
    }

    async fn write(self, manifest_list: ManifestListV1) -> Result<()> {
        ...
    }
}

struct ManifestListWriterV2 {
    output_file: OutputFile,
    snapshot_id: i64,
    parent_snapshot_id: i64,
    sequence_number: i64,
}

impl ManifestListWriterV2 {
    fn new(
        output_file: OutputFile, 
        snapshot_id: i64, 
        parent_snapshot_id: i64, 
        sequence_number: i64
    ) -> ManifestListWriterV2 {
        ...
    }

    async fn write(self, manifest_list: ManifestListV2) -> Result<()> {
        ...
    }
}
```

**Comment by ZENOTME** [comment]
We can integrate V1 and V2 into a writer

```
struck ManifestListWriter {
   ...
}

impl ManifestListWriter {
  fn write_v1(&mut self, manifest_list: ManifestList) {
  }
  
  fn write_v2(&mut self, manifest_list: ManifestList) {
  }
}
```

And we can store the version in ManifestList so that we can just use `write(&mut self manifest_list: ManifestList)`.

**Comment by ZENOTME** [comment]
cc @liurenjie1024  @Xuanwo @JanKaul @Fokko

**Comment by liurenjie1024** [comment]
> Thanks! We can integrate V1 and V2 into a writer
> 
> ```
> struck ManifestListWriter {
>    ...
> }
> 
> impl ManifestListWriter {
>   fn write_v1(&mut self, manifest_list: ManifestList) {
>   }
>   
>   fn write_v2(&mut self, manifest_list: ManifestList) {
>   }
> }
> ```
> 
> And we can store the version in ManifestList so that we can just use `write(&mut self manifest_list: ManifestList)`.

LGTM. The key difference between between v1 and v2 are the avro schema, which should be determinted in constructor.

**Comment by barronw** [comment]
Thanks for the feedback folks! How do we feel about something like this?

```rust
struct ManifestListWriter {
    output_file: OutputFile,
    format_version: FormatVersion,
    avro_schema: AvroSchema,
    metadata: HashMap<String, String>,
}

impl ManifestListWriter {
    pub fn new(
        output_file: OutputFile,
        format_version: FormatVersion,
        metadata: HashMap<String, String>,
    ) -> ManifestListWriter {
        let schema = match format_version {
            FormatVersion::V1 => ManifestList::v1_schema(),
            FormatVersion::V2 => ManifestList::v2_schema(),
        };
        let avro_schema = schema_to_avro_schema("manifest_list", &schema).unwrap();
        Self {
            output_file,
            format_version,
            avro_schema,
            metadata,
        }
    }

    async fn write(self, manifest_list: ManifestList) {
        ...
    }
}
```

Should we support appending entries like the Java and Python implementations instead of a single write?

**Comment by liurenjie1024** [comment]
> Should we support appending entries like the Java and Python implementations instead of a single write?

The `ManifestList` is a simple wrapper of `Vec`, so I think providing a method for iterator of entries would not be huge effort.

**Comment by ZENOTME** [comment]
> Should we support appending entries like the Java and Python implementations instead of a single write?
>> The ManifestList is a simple wrapper of Vec, so I think providing a method for iterator of entries would not be huge effort.

Providing a method for iterator of entries looks good to me, it can be consider as similar to appending entries. 

And I'm curious the benefit of this interface?🤔 (The potential benefit I guess is that we can combine mutiple ManifestList into one.

**Comment by barronw** [comment]
> The ManifestList is a simple wrapper of Vec, so I think providing a method for iterator of entries would not be huge effort.

I'm not sure I'm following. To clarify, I was wondering if we should have something like

```rust
struct ManifestListWriter {
    ...,
    writer: apache_avro::Writer,
}

impl ManifestListWriter {
    fn append(entries: ManifestList) {
        // Append entries to Avro writer
    }

    fn close() {
        // Close Avro writer
    } 
}
```

This is a bit complex though, since the [Avro writer](https://docs.rs/apache-avro/latest/apache_avro/struct.Writer.html) has a reference to the Avro schema.

**Comment by liurenjie1024** [comment]
> > The ManifestList is a simple wrapper of Vec, so I think providing a method for iterator of entries would not be huge effort.
> 
> I'm not sure I'm following. To clarify, I was wondering if we should have something like
> 
> ```rust
> struct ManifestListWriter {
>     ...,
>     writer: apache_avro::Writer,
> }
> 
> impl ManifestListWriter {
>     fn append(entries: ManifestList) {
>         // Append entries to Avro writer
>     }
> 
>     fn close() {
>         // Close Avro writer
>     } 
> }
> ```
> 
> This is a bit complex though, since the [Avro writer](https://docs.rs/apache-avro/latest/apache_avro/struct.Writer.html) has a reference to the Avro schema.

I don't think we should have this, the java writer appends `ManifestFile`, e.g. `ManifestListEntry`.

I was saying we should have sth like:
```rust
impl ManifestListWriter {
 fn append(&mut self, entries: impl Iterator<Item=ManifestListEntry>>) {
 }
}
```
