### ISSUE TITLE
Sort Order Replacement API

### ISSUE THREAD

**Issue by c-thiel** [apache/iceberg-rust#734]
As part of the `Transaction` we need a way to replace the sort order (and by this evolving it).  In Java this is handled by [BaseReplaceSortOrder implements ReplaceSortOrder](https://github.com/apache/iceberg/blob/163e2068f96f139632488f36928bf443c9be326f/core/src/main/java/org/apache/iceberg/BaseReplaceSortOrder.java#L34), which is constructed by the [replaceSortOrder() method](https://github.com/apache/iceberg/blob/163e2068f96f139632488f36928bf443c9be326f/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L155). We should add this method to rust too.

At the time of issue creation, this seems to not be implemented by pyiceberg.

**Comment by flaneur2020** [comment]
take :)

**Comment by flaneur2020** [comment]
sorry i found there's already have a `replace_sort_order` in [transaction.rs](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/transaction.rs#L150) and a `add_sort_order` in [table_metadata_builder.rs](https://github.com/apache/iceberg-rust/blob/main/crates/iceberg/src/spec/table_metadata_builder.rs#L751) implemented in the code base.

i suppose this issue could be marked as closed? or if there is anything else that I may have missed, please let me know.

thanks
