### ISSUE TITLE
Write `null` for `current-snapshot-id`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-rust#752]
Based on the checks in https://github.com/apache/iceberg-rust/pull/742#issuecomment-2515564242, it looks like we write `-1` when there is no snapshot, which is not correct.

**Comment by c-thiel** [comment]
@Fokko for this field but also others (properties, snapshots themselves, snapshot_log) should we skip serializing them if they are none or add `null`?

**Comment by Fokko** [comment]
The [`writer-requirements` sections of the spec](https://iceberg.apache.org/spec/#writer-requirements) clarifies this:

![image](https://github.com/user-attachments/assets/1e628e30-ffb8-4e70-84cf-b2a190e9b296)

The `current-snapshot-id` may be missing too since it is optional in V1. I think it is also fine for `properties`, `snapshots`, and `snapshot-log` to be missing if they are empty, this should all be handled fine by the reader.
