### ISSUE TITLE
Add s3tables catalog support

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#754]
AWS announced a new product called S3 Tables, which allows using a bucket as an Iceberg catalog: https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-s3-tables-apache-iceberg-tables-analytics-workloads/

The API can be found at: https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3tables/src/main/resources/codegen-resources/service-2.json

It should be possible for iceberg-rust to support such a catalog.

**Comment by flaneur2020** [comment]
please assign this to me if it's not a feature that needs to be released soon. I can work on it part-time, but I cannot guarantee the completion time
