### ISSUE TITLE
struct value design

### ISSUE THREAD

**Issue by ZENOTME** [apache/iceberg-rust#77]
Use lookup will make the memory cost if we have multiple struct with same type.

One solve way is to use `Arc<StructType>` in Struct. I try this design in https://github.com/icelake-io/icelake/pull/136. 

Anyway I think it's ok to solve this Problem in another PR. If this desgin looks work, I'm glad to port it.

_Originally posted by @ZENOTME in https://github.com/apache/iceberg-rust/pull/20#discussion_r1282598302_

**Comment by ZENOTME** [comment]
cc @JanKaul @Fokko @Xuanwo  @liurenjie1024

**Comment by liurenjie1024** [comment]
> Another solution is pass struct type as another parameter when we need it, e.g.

I prefer this approach. It's weird for me to store types with values, and we can always to attach type to it when necessary.
