### ISSUE TITLE
Eagerly project arrow schema when calculating the parquet `ProjectionMask`

### ISSUE THREAD

**Issue by gruuya** [apache/iceberg-rust#784]
This is related to #783, but it's more general.

Namely, presently the entire arrow schema is converted to an iceberg schema when determining the `ProjectionMask`, not making use of the projected fields
https://github.com/apache/iceberg-rust/blob/42aff04658a00b390122260dbbeaf512d11af61f/crates/iceberg/src/arrow/reader.rs#L309

This in turn means that even though the subset of the projected fields could have data types which are supported, even if there's a single (non-projected) field with a unsupported data type the entire query will fail.

So ideally the iceberg schema should be converted only from the subset of projected fields.

**Comment by Fokko** [comment]
Thanks @gruuya That would be a great addition. I think we should only project the needed fields anyway.

I was doing some testing along the same line, and also noticed that we don't properly support type widening: https://github.com/apache/iceberg-rust/pull/786
