### ISSUE TITLE
How to release

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-rust#81]
Hi everyone,

It might be premature, but when releasing we need the two guides:

- `how-to-release.md`
- `verify-release.md`

Just to put it out here, and maybe someone is interested in working on this 👍 

Example from PyIceberg ([how-to-release](https://py.iceberg.apache.org/how-to-release/), [verify-release](https://py.iceberg.apache.org/verify-release/)) or Java ([how-to-release](https://iceberg.apache.org/how-to-release/), [verify-release](https://iceberg.apache.org/how-to-release/#how-to-verify-a-release)).

**Comment by liurenjie1024** [comment]
CC @Xuanwo Are you interested in this? I think you are familiar with these stuff.

**Comment by Xuanwo** [comment]
Sure, let me do this!

**Comment by Xuanwo** [comment]
I will add into our website only it's ready.

**Comment by Xuanwo** [comment]
## Tasks

- [ ] Add release docs: https://github.com/apache/iceberg-rust/pull/147
- [ ] Add verify docs
- [ ] Add CI to upload crates

**Comment by Xuanwo** [comment]
All work have been done, let's close.
