### ISSUE TITLE
Substitue in memory data struct's timestamp type for DataTime rather i64 to simplify usage.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#90]
Could we return a Datetime for simpler usage?

_Originally posted by @Xuanwo in https://github.com/apache/iceberg-rust/pull/89#discussion_r1377423426_

**Comment by my-vegetable-has-exploded** [comment]
I‘d like to have a try.

**Comment by liurenjie1024** [comment]
> I‘d like to have a try.

Sure, welcome to contribute!

**Comment by my-vegetable-has-exploded** [comment]
Shall we use DateTime<Utc> here？

**Comment by liurenjie1024** [comment]
> Shall we use ```chrono::DateTime<Utc>``` here？
 I think it's great.

**Comment by fqaiser94** [comment]
Welp, I started looking at this ticket before the most recent comments :S 
I went with `chrono::DateTime<Utc>` as well but had to wrap it in a NewType to implement some traits. 
Not sure how far you got @my-vegetable-has-exploded but if you have a better approach, we can close my PR: https://github.com/apache/iceberg-rust/pull/94

**Comment by my-vegetable-has-exploded** [comment]
> Welp, I started looking at this ticket before the most recent comments :S I went with `chrono::DateTime<Utc>` as well but had to wrap it in a NewType to implement some traits. Not sure how far you got @my-vegetable-has-exploded but if you have a better approach, we can close my PR: #94

Don't worry， you can go ahead and complete the issue.
