### ISSUE TITLE
refactor: Remove `datatype()` method in `Literal`.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#95]
Per [discussion](https://github.com/apache/iceberg-rust/pull/82#discussion_r1392079536), we should remove  [this method](https://github.com/apache/iceberg-rust/blob/28d7006ba3af12b1f99dc078780b08ccdd8e93b1/crates/iceberg/src/spec/values.rs#L910)

**Comment by mobley-trent** [comment]
If this is still open I think I can work on it @liurenjie1024

**Comment by liurenjie1024** [comment]
> If this is still open I think I can work on it @liurenjie1024

Cool, thanks!

**Comment by mobley-trent** [comment]
Actually I think this is already done

**Comment by liurenjie1024** [comment]
> Actually I think this is already done

Oh, sorry, my bad. Let's close this now.
