### ISSUE TITLE
refactor: Remove type infromation in `Struct` literal.

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#96]
According to discussion in #77 , we should remove type information(`field_ids`, `field_names`) in `Struct` literal, also the iterator should not return type informations such as `field_id`, `field_name`.

**Comment by mobley-trent** [comment]
Hey @liurenjie1024 I think I can work on this. Could you assign it to me ?

**Comment by liurenjie1024** [comment]
> Hey @liurenjie1024 I think I can work on this. Could you assign it to me ?

Sure, welcome to contribute.

**Comment by ZhengLin-Li** [comment]
@liurenjie1024 shall we close this as it is solved by https://github.com/apache/iceberg-rust/pull/103

**Comment by liurenjie1024** [comment]
> @liurenjie1024 shall we close this as it is solved by #103

Yes, we can close it now.
