### ISSUE TITLE
feat: Add support for `UnboundSortOrder`

### ISSUE THREAD

**Issue by liurenjie1024** [apache/iceberg-rust#99]
See [java implementation](https://github.com/apache/iceberg/blob/ede085d0f7529f24acd0c81dd0a43f7bb969b763/api/src/main/java/org/apache/iceberg/UnboundSortOrder.java#L28) as reference.

**Comment by fqaiser94** [comment]
I will give this a try, started looking into it.

**Comment by liurenjie1024** [comment]
> I will give this a try, started looking into it. 

Thanks!
